/* ---------- exercise coaching data (Workout / Battle mode) ----------
   Extends each EX entry (js/data.js) by id — EX itself stays untouched.
   difficulty = EX.lvl, equipment = EX.eq, rest = repScheme().

   mode   'reps' → score is counted reps | 'time' → score is seconds held
   dur    default session length in seconds (reps mode) / target hold (time mode)
   pace   AI target reps per 60s at Intermediate (time mode: seconds held)
   pose   rule id in js/pose-rules.js, or null = camera shows the skeleton
          only and reps are counted manually (no auto-count claim)
   muscles  M_NAMES keys, primary first
   form / mistakes / tips  {mn:[...], en:[...]} exercise-specific cues
   prog   progression ladder, easiest → hardest; step = index of THIS exercise */
const COACH = {
  pushup:{mode:'reps', dur:30, pace:35, pose:'pushup', muscles:['chest','shoulders','arms'],
    form:{mn:['Толгой хүзүүгээ саармаг — харц шалны урд хэсэг рүү','Толгойноос өсгий хүртэл бие шулуун шугам','Гар мөрний доор эсвэл арай өргөн','Тохой биеэс 30–45° өнцгөөр хяналттай нугална','Цээж шалнаас нэг нударга хүртэл буух','Дээш түлхэхдээ гараа бүрэн, хяналттай тэнийлгэнэ'],
          en:['Head neutral — eyes on the floor just ahead','Straight line from head to heels','Hands under or slightly wider than shoulders','Elbows bend with control at 30–45° from the body','Chest lowers to about a fist from the floor','Push back up to a full, controlled extension']},
    mistakes:{mn:['Бэлхүүс унжих буюу өгзөг дээш өргөгдөх','Хагас хүрээтэй буух','Тохой хажуу тийш 90° дэлгэгдэх'],
              en:['Hips sagging or piking up','Only lowering halfway','Elbows flaring straight out to 90°']},
    tips:{mn:['Өгзөг, гэдсээ чангалж биеэ нэг банз шиг барь','Буухдаа 2 тоолж, түлхэхдээ 1 тоол'],
          en:['Squeeze glutes and abs so your body moves as one plank','Lower for a count of 2, push for a count of 1']},
    prog:[{mn:'Хана түшсэн push-up',en:'Wall push-up'},{mn:'Налуу (incline) push-up',en:'Incline push-up'},{mn:'Өвдөг дээрх push-up',en:'Knee push-up'},{mn:'Стандарт push-up',en:'Standard push-up'},{mn:'Diamond push-up',en:'Diamond push-up'},{mn:'Decline push-up',en:'Decline push-up'}], step:3},

  squat:{mode:'reps', dur:30, pace:40, pose:'squat', muscles:['legs','glutes'],
    form:{mn:['Хөл мөрний өргөнтэй, ул бүхэлдээ газарт тогтвортой','Өвдөг хөлийн хурууны чигт','Цээж өргөөстэй, нуруу саармаг','Өгзгөө ар, доош суулгана','Гуя газартай зэрэгцэх хүртэл буух','Өсгийгөөр түлхэж хяналттай босно'],
          en:['Feet shoulder-width, whole foot planted','Knees track in line with your toes','Chest up, spine neutral','Send hips back and down','Lower until thighs are about parallel','Drive through your heels and rise with control']},
    mistakes:{mn:['Өвдөг дотогшоо орох','Өсгий газраас салах','Цээж урагш хэт унах'],
              en:['Knees caving inward','Heels lifting off the floor','Chest collapsing forward']},
    tips:{mn:['Гараа урагш сунгавал тэнцвэр амар болно','Доод цэгт амьсгалаа барьж, босохдоо гарга'],
          en:['Reaching your arms forward helps balance','Brace at the bottom, exhale as you stand']},
    prog:[{mn:'Сандал руу суух',en:'Box/chair squat'},{mn:'Bodyweight squat',en:'Bodyweight squat'},{mn:'Pause squat (доод цэгт 2 сек)',en:'Pause squat (2s at bottom)'},{mn:'Jump squat',en:'Jump squat'},{mn:'Bulgarian split squat',en:'Bulgarian split squat'}], step:1},

  lunge:{mode:'reps', dur:30, pace:30, pose:'lunge', muscles:['legs','glutes'],
    form:{mn:['Урагш том алхам, хөл хип-ийн өргөнтэй','Урд өвдөг хурууны чигт, хяналттай','Их бие босоо, цээж өргөөстэй','Хойд өвдгөө шал руу буулгана','Хоёр өвдөг ойролцоогоор 90°','Урд хөлийн өсгийгөөр түлхэж буцна'],
          en:['Big step forward, feet hip-width apart','Front knee tracks over your toes with control','Torso upright, chest lifted','Lower your back knee toward the floor','Both knees reach roughly 90°','Push through the front heel to return']},
    mistakes:{mn:['Урд өвдөг хурууны үзүүрээс хэт давах','Их бие урагш бөхийх','Хоёр хөл нэг шугам дээр тавьж тэнцвэр алдах'],
              en:['Front knee shooting far past the toes','Leaning the torso forward','Feet on one line, losing balance']},
    tips:{mn:['Хол биш, доош чиглэн хөдөл','Хоёр хөлөө ээлжлэн тоол'],
          en:['Think "down", not "forward"','Alternate legs and count each side']},
    prog:[{mn:'Сандал барьсан split squat',en:'Supported split squat'},{mn:'Reverse lunge',en:'Reverse lunge'},{mn:'Forward lunge',en:'Forward lunge'},{mn:'Walking lunge',en:'Walking lunge'},{mn:'Jump lunge',en:'Jump lunge'}], step:2},

  glute:{mode:'reps', dur:30, pace:35, pose:'bridge', muscles:['glutes','legs'],
    form:{mn:['Нуруугаараа хэвтэж өвдгөө нугал, ул шалан дээр','Өсгий өгзөгнөөс 20–30 см зайтай','Өгзгөө чангалж аарцгаа өргөнө','Дээд цэгт мөр–аарцаг–өвдөг нэг шугам','Дээр 1 сек барина','Удаан, хяналттай буулгана'],
          en:['Lie on your back, knees bent, feet flat','Heels about 20–30 cm from your glutes','Squeeze glutes to lift the hips','At the top: shoulders, hips and knees in one line','Hold 1 second at the top','Lower slowly with control']},
    mistakes:{mn:['Бэлхүүсээрээ хэт хотойх','Өгзгөө чангалахгүй өргөх','Хөлийн хуруугаар түлхэх'],
              en:['Overarching the lower back','Lifting without squeezing the glutes','Pushing through the toes']},
    tips:{mn:['Хавиргаа доош "түгжиж" бэлхүүсээ хамгаал','Өсгийгөөр шал түлхэж буй мэт мэдэр'],
          en:['Keep ribs down to protect the lower back','Feel like you are pushing the floor away with your heels']},
    prog:[{mn:'Glute bridge',en:'Glute bridge'},{mn:'Дээд цэгт 3 сек барих bridge',en:'Bridge with 3s hold'},{mn:'Нэг хөлтэй bridge',en:'Single-leg bridge'},{mn:'Hip thrust (сандал түшсэн)',en:'Bench-supported hip thrust'}], step:0},

  plank:{mode:'time', dur:45, pace:60, pose:'plank', muscles:['abs','shoulders'],
    form:{mn:['Тохой мөрний яг доор','Толгой саармаг, хүзүү сунгаастай','Мөр тогтвортой, шал руу түлхэнэ','Мөр–аарцаг–өсгий нэг шугам','Гэдэс, өгзгөө чанга барина','Жигд амьсгална'],
          en:['Elbows directly under shoulders','Head neutral, neck long','Shoulders stable, pushing the floor away','Shoulders, hips and heels in one line','Core and glutes tight','Keep breathing steadily']},
    mistakes:{mn:['Аарцаг доош унжих','Өгзөг дээш өргөгдөх','Амьсгалаа барих'],
              en:['Hips sagging toward the floor','Hips piking up','Holding your breath']},
    tips:{mn:['Хэлбэр алдагдвал зогсоод дахин эхэл — хугацаанаас техник чухал','Тохойгоо хөл рүү татаж буй мэт гэдсээ идэвхжүүл'],
          en:['If form breaks, stop and reset — quality beats time','Pull elbows toward toes to switch the core on']},
    prog:[{mn:'Өвдөг дээрх plank',en:'Knee plank'},{mn:'Plank',en:'Forearm plank'},{mn:'Plank + мөр тогших',en:'Plank shoulder taps'},{mn:'Plank + хөл өргөх',en:'Plank with leg lift'},{mn:'RKC plank',en:'RKC plank'}], step:1},

  mtclimb:{mode:'reps', dur:30, pace:40, pose:null, muscles:['abs','shoulders','cardio'],
    form:{mn:['Гар мөрний доор, өндөр plank байрлал','Аарцаг мөртэй тэгш','Өвдгөө ээлжлэн цээж рүү татна','Хөлийн хуруугаар хөнгөн газардана','Нуруу шулуун хэвээр'],
          en:['High plank, hands under shoulders','Hips level with shoulders','Drive knees alternately toward the chest','Land lightly on the balls of the feet','Back stays straight']},
    mistakes:{mn:['Өгзөг дээш үсэрч plank алдагдах','Мөр гарнаас хойш гарах','Хурдыг техникээс илүү тавих'],
              en:['Hips bouncing up','Shoulders drifting behind the hands','Chasing speed over form']},
    tips:{mn:['Хоёр хөлийн нэг бүтэн хос = 1 давталт','Эхлээд удаан, хэлбэр тогтсоны дараа хурдасга'],
          en:['One left + one right = 1 rep','Start slow; speed up once the form is solid']},
    prog:[{mn:'Удаан mountain climber',en:'Slow mountain climber'},{mn:'Mountain climber',en:'Mountain climber'},{mn:'Cross-body climber',en:'Cross-body climber'},{mn:'Spider climber',en:'Spider climber'}], step:1},

  burpee:{mode:'reps', dur:45, pace:15, pose:null, muscles:['cardio','legs','chest'],
    form:{mn:['Сууж гараа хөлийн өмнө шалан дээр тавина','Хөлөө ухасхийж шулуун plank болно','Хөлөө гар руу буцааж татна','Цээж өргөөстэй дээш үсэрнэ','Зөөлөн, өвдгөө нугалан газардана'],
          en:['Squat down, hands on the floor in front of the feet','Jump the feet back to a straight plank','Jump the feet back in toward the hands','Jump up with the chest tall','Land softly with bent knees']},
    mistakes:{mn:['Plank үед бэлхүүс унжих','Хатуу газардах','Амьсгаагүй хэт хурдлах'],
              en:['Hips sagging in the plank','Landing stiff-legged','Rushing without breathing']},
    tips:{mn:['Хэмнэлээ барь — тогтмол хурд илүү олон давталт өгнө','Ядарвал үсрэлтгүй хувилбар руу шилж'],
          en:['Keep a steady rhythm — it adds up to more reps','Switch to no-jump when tired']},
    prog:[{mn:'Алхаж хийх burpee',en:'Step-back burpee'},{mn:'Үсрэлтгүй burpee',en:'No-jump burpee'},{mn:'Burpee',en:'Burpee'},{mn:'Push-up нэмсэн burpee',en:'Burpee with push-up'},{mn:'Tuck jump burpee',en:'Tuck-jump burpee'}], step:2},

  pikepu:{mode:'reps', dur:30, pace:20, pose:'pike', muscles:['shoulders','arms'],
    form:{mn:['Өгзгөө өндөр өргөж урвуу "V" хэлбэр','Гар мөрний өргөнтэй','Толгойгоо гарын хооронд шал руу буулгана','Тохой урагш-хажуу 45° нугална','Мөрөөр түлхэж буцна'],
          en:['Hips high in an inverted "V"','Hands shoulder-width apart','Lower the head between the hands toward the floor','Elbows bend forward-out at about 45°','Press back up through the shoulders']},
    mistakes:{mn:['Өгзөг доош унаж энгийн push-up болох','Тохой хажуу тийш дэлгэгдэх','Хагас хүрээтэй'],
              en:['Hips dropping into a normal push-up','Elbows flaring sideways','Partial range of motion']},
    tips:{mn:['Хөлөө гар руу ойртуулах тусам мөрөнд илүү ачаалал','Толгой, гар хоёр гурвалжин үүсгэнэ'],
          en:['Walking feet closer loads the shoulders more','Head and hands form a triangle']},
    prog:[{mn:'Хана түшсэн pike hold',en:'Wall pike hold'},{mn:'Pike push-up',en:'Pike push-up'},{mn:'Хөл өндөрт pike push-up',en:'Elevated pike push-up'},{mn:'Хана түшсэн handstand push-up',en:'Wall handstand push-up'}], step:1},

  superman:{mode:'reps', dur:30, pace:20, pose:null, muscles:['back','glutes'],
    form:{mn:['Гэдсээрээ хэвтэж гараа урагш сунгана','Гар, хөлөө зэрэг бага зэрэг өргөнө','Хүзүү саармаг — харц шал руу','Дээр 2 сек барина','Удаан буулгана'],
          en:['Lie face down, arms reaching forward','Lift arms and legs together a few centimetres','Neck neutral — eyes down','Hold 2 seconds at the top','Lower slowly']},
    mistakes:{mn:['Толгойгоо хэт дээш гэдийлгэх','Огцом савлах','Хэт өндөр өргөж бэлхүүс чилээх'],
              en:['Cranking the head back','Swinging up with momentum','Lifting too high and straining the low back']},
    tips:{mn:['Өндрөөс илүү сунгалтыг мэдэр','Өгзгөө чангалбал бэлхүүс хамгаалагдана'],
          en:['Think length, not height','Squeezing the glutes protects the low back']},
    prog:[{mn:'Зөвхөн гар эсвэл хөл',en:'Arms-only or legs-only'},{mn:'Superman',en:'Superman'},{mn:'Superman 5 сек барих',en:'Superman 5s hold'},{mn:'Superman + гар сэлэлт',en:'Superman with swimmers'}], step:1},

  birddog:{mode:'reps', dur:30, pace:20, pose:null, muscles:['back','abs'],
    form:{mn:['Дөрвөн хөллөж гар мөрний доор, өвдөг хипийн доор','Нуруу ширээ шиг тэгш','Эсрэг гар, хөлөө зэрэг сунгана','Аарцаг эргэхгүй тэгш','2 сек барьж ээлжилнэ'],
          en:['On all fours: hands under shoulders, knees under hips','Back flat like a table','Extend the opposite arm and leg together','Hips stay square — no rotation','Hold 2 seconds, then switch']},
    mistakes:{mn:['Аарцаг хажуу тийш эргэх','Бэлхүүс хотойх','Хэт хурдан солих'],
              en:['Hips rotating open','Low back arching','Switching sides too fast']},
    tips:{mn:['Нуруун дээр аяга ус тавьсан гэж төсөөл','Хоёр тал = 1 давталт'],
          en:['Imagine a glass of water on your back','Both sides = 1 rep']},
    prog:[{mn:'Зөвхөн хөл сунгах',en:'Leg-only reach'},{mn:'Bird dog',en:'Bird dog'},{mn:'Bird dog тохой–өвдөг',en:'Bird dog elbow-to-knee'},{mn:'Резинтэй bird dog',en:'Banded bird dog'}], step:1},

  bicycle:{mode:'reps', dur:30, pace:40, pose:null, muscles:['abs'],
    form:{mn:['Нуруу доод хэсэг шалнаас салахгүй','Гараа толгойны хажууд хөнгөн','Мөрөө өргөж тохойгоо эсрэг өвдөг рүү эргүүлнэ','Нөгөө хөл урагш сунгагдана','Удаан, хяналттай эргэлт'],
          en:['Low back stays pressed to the floor','Fingertips lightly by the head','Lift shoulders and rotate elbow toward the opposite knee','The other leg extends long','Slow, controlled rotation']},
    mistakes:{mn:['Гараар хүзүүгээ татах','Зөвхөн тохой хөдөлгөж их бие эргэхгүй','Хэт хурдлах'],
              en:['Pulling on the neck','Moving only the elbows, not the torso','Going too fast']},
    tips:{mn:['Мөрөө өвдөг рүү эргүүлнэ гэж бод','Баруун + зүүн эргэлт = 1 давталт'],
          en:['Think shoulder-to-knee, not elbow-to-knee','Right + left twist = 1 rep']},
    prog:[{mn:'Dead bug',en:'Dead bug'},{mn:'Bicycle crunch',en:'Bicycle crunch'},{mn:'Удаан 3-тоолт bicycle',en:'Slow 3-count bicycle'},{mn:'Хөл намхан bicycle',en:'Low-leg bicycle'}], step:1},

  wallsit:{mode:'time', dur:40, pace:45, pose:'wallsit', muscles:['legs','glutes'],
    form:{mn:['Нуруу бүхэлдээ ханад наалдана','Өвдөг, хип 90° орчим','Өвдөг шагайн дээгүүр, хурууны чигт','Жин өсгий дээр','Гараа гуян дээр түшихгүй'],
          en:['Whole back flat against the wall','Knees and hips at about 90°','Knees stacked over ankles, in line with toes','Weight in the heels','Hands off the thighs']},
    mistakes:{mn:['Хэт өндөр суух','Өвдөг дотогш орох','Гараараа гуяа түлхэх'],
              en:['Sitting too high','Knees caving in','Pushing on the thighs with the hands']},
    tips:{mn:['Хугацааг хэсэгчлэн тоол: 10 + 10 + 10','Амьсгаагаа жигд барь'],
          en:['Break the time into chunks: 10 + 10 + 10','Keep breathing evenly']},
    prog:[{mn:'Өндөр wall sit',en:'High wall sit'},{mn:'Wall sit 90°',en:'Wall sit at 90°'},{mn:'Wall sit + өсгий өргөх',en:'Wall sit with heel raise'},{mn:'Нэг хөлтэй wall sit',en:'Single-leg wall sit'}], step:1},

  jjack:{mode:'reps', dur:30, pace:60, pose:'jack', muscles:['cardio','legs'],
    form:{mn:['Босоо, гэдэс бага зэрэг чанга','Үсрэхдээ хөлөө мөрнөөс өргөн','Гараа толгойн дээр хүргэнэ','Хөлийн хуруун дээр зөөлөн газардана','Тогтмол хэмнэл'],
          en:['Stand tall, core lightly braced','Jump feet out wider than shoulders','Arms reach overhead','Land softly on the balls of the feet','Keep a steady rhythm']},
    mistakes:{mn:['Хатуу, өсгий дээр газардах','Гараа дутуу өргөх','Мөрөө чангалж хүзүү чилээх'],
              en:['Landing hard on the heels','Arms stopping short','Shrugging and tensing the neck']},
    tips:{mn:['Нээгдээд хаагдах бүтэн мөчлөг = 1 давталт','Өвдөг хөнгөн нугалаастай'],
          en:['Out and back in = 1 rep','Keep a soft bend in the knees']},
    prog:[{mn:'Алхаж хийх jack',en:'Step jack'},{mn:'Jumping jack',en:'Jumping jack'},{mn:'Seal jack',en:'Seal jack'},{mn:'Squat jack',en:'Squat jack'}], step:1},

  calf:{mode:'reps', dur:30, pace:40, pose:null, muscles:['legs'],
    form:{mn:['Хөл хипийн өргөнтэй, босоо','Хөлийн хуруун дээр аль болох өндөр гарна','Шагай гадагш хазайхгүй','Хамгийн өндөр цэгт 1 сек зогсоно','Өсгийгөө удаан шал руу буулгана'],
          en:['Feet hip-width, standing tall','Rise as high as possible onto the balls of the feet','Ankles stay straight, not rolling out','Pause 1 second at the highest point','Lower the heels slowly to the floor']},
    mistakes:{mn:['Доош огцом унах','Хагас өргөх','Биеэ урагш бөхийлгөх'],
              en:['Dropping down fast','Half-height reps','Leaning the body forward']},
    tips:{mn:['Буухдаа 3 тоол','Шатан дээр хийвэл хүрээ томорно'],
          en:['Take 3 counts to lower','A step edge adds range of motion']},
    prog:[{mn:'Хана түшсэн calf raise',en:'Supported calf raise'},{mn:'Calf raise',en:'Calf raise'},{mn:'Шатан дээрх calf raise',en:'Step calf raise'},{mn:'Нэг хөлтэй calf raise',en:'Single-leg calf raise'}], step:1},

  bench:{mode:'reps', dur:45, pace:15, pose:null, muscles:['chest','arms','shoulders'],
    form:{mn:['Нүд барбеллын доор, ул шалан дээр тогтвортой','Мөрний ир доош, ар руу шахаастай','Барих өргөн мөрнөөс арай өргөн','Барбеллыг цээжний доод хэсэг рүү хяналттай буулгана','Тохой биеэс 45–70°','Мөрний дээгүүр шулуун түлхэнэ'],
          en:['Eyes under the bar, feet planted','Shoulder blades pinned down and back','Grip slightly wider than shoulders','Lower the bar with control to the lower chest','Elbows at 45–70° from the body','Press straight up over the shoulders']},
    mistakes:{mn:['Өгзгөө сандлаас өргөх','Барбеллыг цээжнээс ойж түлхэх','Тохойг 90° дэлгэх'],
              en:['Lifting the hips off the bench','Bouncing the bar off the chest','Flaring elbows to 90°']},
    tips:{mn:['Хүнд жинтэй бол заавал хамгаалагчтай хий','Буухдаа амьсгаа авч, түлхэхдээ гарга'],
          en:['Always use a spotter for heavy sets','Inhale on the way down, exhale as you press']},
    prog:[{mn:'Push-up',en:'Push-up'},{mn:'Dumbbell bench press',en:'Dumbbell bench press'},{mn:'Barbell bench press',en:'Barbell bench press'},{mn:'Pause bench press',en:'Pause bench press'}], step:2},

  inclinedb:{mode:'reps', dur:45, pace:15, pose:null, muscles:['chest','shoulders','arms'],
    form:{mn:['Сандал 30–45° налуу','Мөрний ир сандалд шахаастай','Гантель цээжний дээд хэсгийн хажууд эхэлнэ','Тохой бага зэрэг дотогш','Дээш түлхэхдээ гантель ойртоно, мөргөлдөхгүй'],
          en:['Bench set to 30–45°','Shoulder blades pressed into the bench','Dumbbells start beside the upper chest','Elbows tucked slightly','Press up so the dumbbells come together without clashing']},
    mistakes:{mn:['Сандал хэт босоо — мөрний дасгал болох','Бэлхүүс хэт хотойх','Гантель огцом буулгах'],
              en:['Bench too upright — it becomes a shoulder press','Excessive lower-back arch','Dropping the dumbbells fast']},
    tips:{mn:['Доод цэгт цээжний сунгалтыг мэдэр','Бугуй тохойн дээр шулуун'],
          en:['Feel the stretch across the chest at the bottom','Wrists stacked over elbows']},
    prog:[{mn:'Incline push-up',en:'Incline push-up'},{mn:'Бага жинтэй incline press',en:'Light incline press'},{mn:'Incline dumbbell press',en:'Incline dumbbell press'},{mn:'Incline barbell press',en:'Incline barbell press'}], step:2},

  latpull:{mode:'reps', dur:45, pace:18, pose:null, muscles:['back','arms'],
    form:{mn:['Гуяа дэвсгэрийн доор бэхэлнэ','Бариулыг мөрнөөс өргөн барина','Цээж өргөж бага зэрэг хойш налж суух','Мөрөө доош буулгаад тохойгоороо татна','Бариул цээжний дээд хэсэгт хүрнэ','Удаан, бүрэн сунгаж буцаана'],
          en:['Thighs locked under the pad','Grip wider than shoulders','Chest up with a slight lean back','Pull shoulders down first, then drive the elbows','Bar reaches the upper chest','Return slowly to a full stretch']},
    mistakes:{mn:['Биеэ хэт хойш савлах','Хүзүүний ард татах','Бариулыг цээж хүртэл татахгүй хагас хүрээтэй'],
              en:['Swinging the body back','Pulling behind the neck','Half range of motion']},
    tips:{mn:['Гараар биш, тохойгоор тат гэж бод','Доод цэгт мөрний ирээ 1 сек шах'],
          en:['Think elbows, not hands','Squeeze the shoulder blades for 1s at the bottom']},
    prog:[{mn:'Резинтэй pulldown',en:'Band pulldown'},{mn:'Lat pulldown',en:'Lat pulldown'},{mn:'Assisted pull-up',en:'Assisted pull-up'},{mn:'Pull-up',en:'Pull-up'}], step:1},

  row:{mode:'reps', dur:45, pace:18, pose:null, muscles:['back','arms'],
    form:{mn:['Хөлөө тавцан дээр, өвдөг бага нугалаастай','Нуруу шулуун, цээж өргөөстэй','Бариулыг хүйс рүү татна','Тохой биед ойр ар тийш','Мөрний ирээ 1 сек шахна','Урагш бүрэн, хяналттай сунгана'],
          en:['Feet on the platform, knees softly bent','Back straight, chest up','Pull the handle toward the belly button','Elbows travel back close to the body','Squeeze shoulder blades for 1 second','Reach forward fully with control']},
    mistakes:{mn:['Бэлхүүсээрээ савлан татах','Мөрөө чих рүү өргөх','Нуруу дугуйрах'],
              en:['Rocking with the lower back','Shrugging shoulders to the ears','Rounding the back']},
    tips:{mn:['Их бие бараг хөдөлгөөнгүй','Буцаахдаа 2 тоол'],
          en:['Torso stays almost still','Take 2 counts on the return']},
    prog:[{mn:'Резинтэй row',en:'Band row'},{mn:'Seated cable row',en:'Seated cable row'},{mn:'Нэг гартай dumbbell row',en:'One-arm dumbbell row'},{mn:'Barbell row',en:'Barbell row'}], step:1},

  deadlift:{mode:'reps', dur:45, pace:10, pose:'hinge', muscles:['back','glutes','legs'],
    form:{mn:['Хөл хипийн өргөнтэй, барбелл хөлийн дунд','Нуруу саармаг, цээж өргөөстэй','Барбеллыг шилбэнд ойр барина','Эхлэхээс өмнө гэдсээ чангална','Хип, өвдөг зэрэг тэнийлгэж босно','Дээд цэгт өгзгөө шахна, хойш хотойхгүй'],
          en:['Feet hip-width, bar over mid-foot','Neutral spine, chest up','Bar kept close to the shins','Brace the core before pulling','Hips and knees extend together','Squeeze glutes at the top — no leaning back']},
    mistakes:{mn:['Нуруу дугуйрах — гэмтлийн эрсдэлтэй','Барбелл биеэс холдох','Дээд цэгт хэт хойш хотойх'],
              en:['Rounding the back — injury risk','Bar drifting away from the body','Hyperextending at the top']},
    tips:{mn:['Шалыг хөлөөрөө түлхэж байна гэж бод','Camera зөвхөн хип нугалах хүрээг хэмжинэ — нурууны дугуйралтыг хэмжихгүй'],
          en:['Think "push the floor away"','The camera measures hip hinge range only — not spinal rounding']},
    prog:[{mn:'Kettlebell deadlift',en:'Kettlebell deadlift'},{mn:'Romanian deadlift',en:'Romanian deadlift'},{mn:'Deadlift',en:'Deadlift'},{mn:'Deficit deadlift',en:'Deficit deadlift'}], step:2},

  squatbb:{mode:'reps', dur:45, pace:15, pose:'squat', muscles:['legs','glutes','abs'],
    form:{mn:['Барбелл мөрний дээд булчин дээр','Хөл мөрний өргөнтэй, хуруу бага гадагш','Амьсгаа авч гэдсээ чангална','Өгзөг ар, доош суулгана','Өвдөг хурууны чигт','Гуя зэрэгцэх хүртэл буугаад өсгийгөөр босно'],
          en:['Bar resting on the upper back','Feet shoulder-width, toes slightly out','Breathe in and brace the core','Sit hips back and down','Knees track with the toes','Reach parallel, then drive up through the heels']},
    mistakes:{mn:['Жин дор өвдөг дотогшоо орох','Цээж урагш унах','Жин урагш шилжиж өсгий салах'],
              en:['Knees caving in under the bar','Chest dropping forward','Heels lifting']},
    tips:{mn:['Хүнд жинтэй бол safety bar буюу хамгаалагчтай','Доод цэгт амьсгалаа бүү гарга'],
          en:['Use safety bars or a spotter when heavy','Hold your brace through the bottom']},
    prog:[{mn:'Goblet squat',en:'Goblet squat'},{mn:'Barbell box squat',en:'Barbell box squat'},{mn:'Barbell squat',en:'Barbell squat'},{mn:'Front squat',en:'Front squat'}], step:2},

  legpress:{mode:'reps', dur:45, pace:18, pose:null, muscles:['legs','glutes'],
    form:{mn:['Нуруу, өгзөг суудалд бүрэн наалдана','Хөл мөрний өргөнтэй тавцангийн дунд','Өвдгөө 90° хүртэл хяналттай нугална','Өвдөг тавцан дээрх хурууны чигт','Түлхэхдээ өвдгөө бүрэн түгжихгүй'],
          en:['Back and hips flat against the seat','Feet shoulder-width, middle of the platform','Bend knees with control to about 90°','Knees track over the toes on the platform','Press without locking the knees']},
    mistakes:{mn:['Өгзөг суудлаас өргөгдөх','Өвдгөө бүрэн түгжих','Хэт гүн буулгаж бэлхүүс дугуйрах'],
              en:['Hips lifting off the seat','Locking the knees out','Going so deep the low back rounds']},
    tips:{mn:['Өсгийгөөр түлх','Буулгахдаа 2–3 тоол'],
          en:['Press through the heels','Take 2–3 counts on the way down']},
    prog:[{mn:'Bodyweight squat',en:'Bodyweight squat'},{mn:'Leg press',en:'Leg press'},{mn:'Нэг хөлтэй leg press',en:'Single-leg leg press'},{mn:'Barbell squat',en:'Barbell squat'}], step:1},

  rdl:{mode:'reps', dur:45, pace:14, pose:'hinge', muscles:['legs','glutes','back'],
    form:{mn:['Өвдөг бага зэрэг нугалаастай, тогтмол','Өгзгөө хойш түлхэж хип-ээр нугална','Нуруу саармаг, мөр ар тийш','Жин гуяны урдуур ойр гулсана','Гуяны ар татагдах хүртэл буулгана','Өгзгөө шахаж босно'],
          en:['Soft, fixed bend in the knees','Push hips back to hinge','Neutral spine, shoulders back','Weight slides down close to the thighs','Lower until the hamstrings stretch','Squeeze glutes to stand up']},
    mistakes:{mn:['Жин буулгахдаа нуруу дугуйрах','Өвдгөө хэт нугалж squat болгох','Жин биеэс холдох'],
              en:['Rounding the back while lowering','Bending the knees into a squat','Weight drifting away from the legs']},
    tips:{mn:['Хаалгыг өгзгөөрөө хаах гэж бод','Хүрээ уян хатан чанараас хамаарна — хүчээр бүү гүнзгийрүүл'],
          en:['Think "close a door with your hips"','Range depends on flexibility — never force depth']},
    prog:[{mn:'Bodyweight hip hinge',en:'Bodyweight hip hinge'},{mn:'Dumbbell RDL',en:'Dumbbell RDL'},{mn:'Barbell RDL',en:'Barbell RDL'},{mn:'Нэг хөлтэй RDL',en:'Single-leg RDL'}], step:2},

  hipthrust:{mode:'reps', dur:45, pace:20, pose:'bridge', muscles:['glutes','legs'],
    form:{mn:['Мөрний ирийн доод хэсэг сандлын ирмэг дээр','Барбелл аарцгийн нугалаас дээр, зөөлөвчтэй','Ул шалан дээр, дээд цэгт шилбэ босоо','Эрүүгээ бага зэрэг доош','Өгзгөө шахаж аарцгаа түлхэнэ','Дээр их бие шалтай зэрэгцэнэ'],
          en:['Lower shoulder blades on the bench edge','Bar padded, sitting in the hip crease','Feet flat; shins vertical at the top','Chin slightly tucked','Squeeze glutes to drive the hips up','Torso parallel to the floor at the top']},
    mistakes:{mn:['Бэлхүүсээр хотойх','Богино хүрээтэй','Хөл хэт хол/ойр'],
              en:['Arching through the lower back','Short range of motion','Feet too far or too close']},
    tips:{mn:['Дээд цэгт 1 сек шахаж барь','Хавиргаа доош түгж'],
          en:['Hold the squeeze for 1s at the top','Keep the ribs down']},
    prog:[{mn:'Glute bridge',en:'Glute bridge'},{mn:'Bodyweight hip thrust',en:'Bodyweight hip thrust'},{mn:'Barbell hip thrust',en:'Barbell hip thrust'},{mn:'Нэг хөлтэй hip thrust',en:'Single-leg hip thrust'}], step:2},

  ohp:{mode:'reps', dur:45, pace:15, pose:'press', muscles:['shoulders','arms'],
    form:{mn:['Гантель мөрний түвшинд, бугуй тохойн дээр','Өгзөг, гэдсээ чангална','Толгойн дээгүүр шулуун түлхэнэ','Дээд цэгт гар бүрэн тэнийнэ','Хяналттай мөрний түвшин рүү буулгана'],
          en:['Dumbbells at shoulder height, wrists over elbows','Glutes and core tight','Press straight overhead','Arms fully extended at the top','Lower with control to shoulder height']},
    mistakes:{mn:['Бэлхүүсээ хойш хотойлгох','Хөлөөр түлхэж савлах','Толгойн дээр бүрэн тэнийлгэхгүй хагас хүрээтэй'],
              en:['Leaning back through the low back','Using leg drive / momentum','Partial range']},
    tips:{mn:['Дээд цэгт толгой гарын дундуур урагш гарна','Сууж хийвэл нуруу хамгаалагдана'],
          en:['Push the head through the arms at the top','Seated variation protects the back']},
    prog:[{mn:'Pike push-up',en:'Pike push-up'},{mn:'Суугаад dumbbell press',en:'Seated dumbbell press'},{mn:'Standing dumbbell press',en:'Standing dumbbell press'},{mn:'Barbell overhead press',en:'Barbell overhead press'}], step:2},

  latraise:{mode:'reps', dur:45, pace:18, pose:'raise', muscles:['shoulders'],
    form:{mn:['Босоо, өвдөг бага нугалаастай','Тохой бага зэрэг нугалаастай хэвээр','Гантелийг хажуу тийш мөрний түвшинд өргөнө','Мөрөө чих рүү өргөхгүй','2–3 тоолж буулгана'],
          en:['Stand tall, knees soft','Keep a slight, fixed elbow bend','Raise the dumbbells out to shoulder height','Keep shoulders away from the ears','Lower over 2–3 counts']},
    mistakes:{mn:['Биеэ савлаж өргөх','Мөрнөөс дээш хэт өргөх','Мөрөө чангалж өргөх'],
              en:['Swinging the body','Lifting far above shoulder height','Shrugging the weight up']},
    tips:{mn:['Хөнгөн жин + удаан tempo хамгийн үр дүнтэй','Тохойгоор хөтөлж өргө'],
          en:['Light weight + slow tempo works best','Lead with the elbows']},
    prog:[{mn:'Резинтэй lateral raise',en:'Band lateral raise'},{mn:'Lateral raise',en:'Lateral raise'},{mn:'Удаан tempo lateral raise',en:'Slow-tempo lateral raise'},{mn:'Cable lateral raise',en:'Cable lateral raise'}], step:1},

  curl:{mode:'reps', dur:45, pace:20, pose:'curl', muscles:['arms'],
    form:{mn:['Тохой биеийн хажууд тогтмол','Бугуй шулуун','Гантелийг мөр рүү эргүүлж өргөнө','Дээд цэгт bicep-ээ шахна','Бүрэн, удаан буулгана'],
          en:['Elbows pinned at your sides','Wrists straight','Curl the dumbbells up toward the shoulders','Squeeze the biceps at the top','Lower fully and slowly']},
    mistakes:{mn:['Биеэ савлах','Тохой урагш гарах','Хагас буулгах'],
              en:['Swinging the torso','Elbows drifting forward','Not lowering all the way']},
    tips:{mn:['Хананд нуруу түшвэл савлах боломжгүй','Буулгах үе дээр 3 тоол'],
          en:['Back against a wall prevents swinging','3 counts on the lowering phase']},
    prog:[{mn:'Резинтэй curl',en:'Band curl'},{mn:'Dumbbell curl',en:'Dumbbell curl'},{mn:'Hammer curl',en:'Hammer curl'},{mn:'Barbell curl',en:'Barbell curl'}], step:1},

  pushdown:{mode:'reps', dur:45, pace:20, pose:null, muscles:['arms'],
    form:{mn:['Кабелийн өмнө босоо, бага зэрэг урагш налсан','Тохой хавирганы хажууд хөдөлгөөнгүй','Бариулыг доош бүрэн тэнийтэл түлхэнэ','Доод цэгт triceps шахна','Тохой хөдөлгөхгүй удаан буцаана'],
          en:['Stand at the cable, slight forward lean','Elbows pinned at the sides','Press the bar down to full extension','Squeeze the triceps at the bottom','Return slowly without moving the elbows']},
    mistakes:{mn:['Тохой урагш-хойш хөдлөх','Биеийн жингээр түлхэх','Хагас хүрээ'],
              en:['Elbows moving forward and back','Pushing with body weight','Stopping short of full lockout']},
    tips:{mn:['Зөвхөн шуу хөдөлнө','Олс ашиглавал доод цэгт салгаж түлх'],
          en:['Only the forearms move','With a rope, split it apart at the bottom']},
    prog:[{mn:'Bench dip (өвдөг нугалаастай)',en:'Bent-knee bench dip'},{mn:'Tricep pushdown',en:'Tricep pushdown'},{mn:'Overhead cable extension',en:'Overhead cable extension'},{mn:'Parallel bar dip',en:'Parallel bar dip'}], step:1},

  cablecr:{mode:'reps', dur:45, pace:20, pose:null, muscles:['abs'],
    form:{mn:['Кабелийн өмнө өвдөглөнө','Олсыг толгойн хажууд барина','Хип хөдөлгөөнгүй','Хавиргаа аарцаг руу нугалж доош бөхийнө','Удаан, хяналттай буцна'],
          en:['Kneel facing the cable','Hold the rope beside your head','Hips stay still','Curl the ribs toward the pelvis','Return slowly with control']},
    mistakes:{mn:['Гараар татах','Хипээр суух хөдөлгөөн хийх','Хэт хүнд жин'],
              en:['Pulling with the arms','Sitting back with the hips','Going too heavy']},
    tips:{mn:['Нуруугаа дугуйлж гэдсээрээ "шахна"','Доод цэгт амьсгаа гарга'],
          en:['Round the spine and crunch through the abs','Exhale fully at the bottom']},
    prog:[{mn:'Crunch',en:'Crunch'},{mn:'Cable crunch',en:'Cable crunch'},{mn:'Hanging knee raise',en:'Hanging knee raise'},{mn:'Hanging leg raise',en:'Hanging leg raise'}], step:1},

  pullup:{mode:'reps', dur:45, pace:10, pose:null, muscles:['back','arms'],
    form:{mn:['Бариулыг мөрнөөс арай өргөн барина','Бүрэн унжиж эхэлнэ','Мөрөө доош "түгжиж" татаж эхэлнэ','Цээжээ бариул руу тат','Эрүү бариулаас дээш гарна','Хяналттай бүрэн буулгана'],
          en:['Overhand grip slightly wider than shoulders','Start from a full hang','Set the shoulders down before pulling','Pull the chest toward the bar','Chin clears the bar','Lower with control to a full hang']},
    mistakes:{mn:['Хөлөөр савлах (kipping)','Эрүү бариулд хүрэхгүй хагас хүрээ','Дээр гарахдаа мөрөө чих рүү өргөх'],
              en:['Kipping with the legs','Half reps','Shrugging the shoulders up']},
    tips:{mn:['Чадахгүй бол резин эсвэл assisted машинаар эхэл','Буух үе (negative) хүчийг хурдан нэмэгдүүлнэ'],
          en:['Use a band or assisted machine to start','Slow negatives build strength fast']},
    prog:[{mn:'Dead hang',en:'Dead hang'},{mn:'Negative pull-up',en:'Negative pull-up'},{mn:'Assisted pull-up',en:'Assisted pull-up'},{mn:'Pull-up',en:'Pull-up'},{mn:'Weighted pull-up',en:'Weighted pull-up'}], step:3},
};

/* localized accessors — never mutate COACH; pick the language at read time */
function coachFor(id){
  const c = COACH[id];
  if(!c) return null;
  const L = (typeof S!=='undefined' && S.lang==='en') ? 'en' : 'mn';
  return {
    ...c,
    form: c.form[L], mistakes: c.mistakes[L], tips: c.tips[L],
    progNames: c.prog.map(p=>p[L]),
    next: c.prog[c.step+1] ? c.prog[c.step+1][L] : null,
    prev: c.step>0 ? c.prog[c.step-1][L] : null,
  };
}
