/* ---------- exercise database (Монгол) ---------- */
// loc: 'home' | 'gym'   m: muscle group   lvl: 1 beg /2 int /3 adv   eq: equipment tag
// goals: this exercise fits which goal filters ('fatloss'|'muscle'|'tone'|'strength'|'health')
// video: YouTube video id ('' = none yet) — see js/views/exercise.js videoEmbed()
const EX = [
  // HOME — bodyweight
  {id:'pushup', n:'Push Up (Шахалт)', e:'🤸', loc:'home', m:'chest', lvl:1, eq:'none', kcal:7, video:'WDIpL0pjun0', goals:['muscle','tone','strength'],
    tgt:'Цээж, мөр, гарын ар (triceps)', tech:'Гараа мөрнөөсөө бага зэрэг өргөн тавь. Бие шулуун — толгойноос өсгий хүртэл нэг шугам. Цээжээ доош буулгаад дээш түлх.',
    err:'Нуруугаа хотойлгох, өгзгөө дээш өргөх. Толгойгоо унжуулах.', easy:'Өвдөг дээрээ push up', hard:'Decline (хөл өндөрт)'},
  {id:'squat', n:'Bodyweight Squat (Суулт)', e:'🦵', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'DlS-GAF8Edg', goals:['muscle','tone','fatloss'],
    tgt:'Гуя (quads), өгзөг', tech:'Хөлөө мөрний өргөнтэй тавь. Өгзгөө ар руу суулгаж, цээжээ өргөж, өвдгөө хурууныхаа чигт чиглүүл.',
    err:'Өвдөг дотогшоо орох, өсгий газраас салах.', easy:'Сандал руу суух', hard:'Jump squat'},
  {id:'lunge', n:'Lunge (Урагшаа алхалт)', e:'🚶', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'g8-Ge9S0aUw', goals:['tone','fatloss'],
    tgt:'Гуя, өгзөг, тэнцвэр', tech:'Урагшаа том алхаад хойд өвдгөө газар руу буулга. Хоёр өвдөг 90°. Өсгийгөөрөө түлхэж буц.',
    err:'Урд өвдөг хурууныхаа чигээс хэт давах.', easy:'Барьц барьж хийх', hard:'Walking lunge / гантельтэй'},
  {id:'glute', n:'Glute Bridge (Өгзгийн гүүр)', e:'🍑', loc:'home', m:'glutes', lvl:1, eq:'none', kcal:5, video:'wPM8icPu6H8', goals:['tone','muscle'],
    tgt:'Өгзөг, гуяны ар', tech:'Нуруугаараа хэвт, өвдгөө нугал. Өгзгөө чангалж аарцгаа дээш өргө. Дээд цэгт 1 сек барь.',
    err:'Бэлхүүсээрээ хотойх. Өгзгөө чангалахгүй байх.', easy:'—', hard:'Нэг хөл дээр'},
  {id:'plank', n:'Plank (Тэвш)', e:'🧘', loc:'home', m:'abs', lvl:1, eq:'none', kcal:4, video:'mwlp75MS6Rg', goals:['tone','health'],
    tgt:'Гэдэс, цөм (core)', tech:'Тохой мөрнийхөө доор. Бие шулуун. Гэдэс, өгзгөө чангал. 20–60 сек барь.',
    err:'Өгзөг дээш/доош, нуруу унжих.', easy:'Өвдөг дээр', hard:'Plank + хөл өргөх'},
  {id:'mtclimb', n:'Mountain Climber', e:'⛰️', loc:'home', m:'abs', lvl:2, eq:'none', kcal:11, video:'ixxk9Qfn61o', goals:['fatloss','health'],
    tgt:'Гэдэс, мөр, зүрх судас', tech:'Plank байрлалаас өвдгөө ээлжлэн цээж рүүгээ хурдан татаж ир. Өгзгөө тэгш барь.',
    err:'Өгзгөө дээш өргөх, хурдыг техникээс түрүүлүүлэх.', easy:'Удаан хийх', hard:'Cross-body хувилбар'},
  {id:'burpee', n:'Burpee', e:'🔥', loc:'home', m:'cardio', lvl:2, eq:'none', kcal:14, video:'wGvBfVeCNko', goals:['fatloss','health'],
    tgt:'Бүх бие, зүрх судас, өөх шатаалт', tech:'Суугаад гараа тавьж, хөлөө ухасхийн plank болж, буцааж татаад дээш үсэр.',
    err:'Нуруу хотойх. Хэт хурдлаад техник алдах.', easy:'Үсрэлтгүй', hard:'Push up нэмэх'},
  {id:'pikepu', n:'Pike Push Up', e:'🔺', loc:'home', m:'shoulders', lvl:2, eq:'none', kcal:7, video:'pHR5yG6xBps', goals:['muscle','tone'],
    tgt:'Мөр (delts), гарын ар', tech:'Өгзгөө дээш өргөж "А" хэлбэр үүсгэ. Толгойгоо газар руу буулгаж дээш түлх.',
    err:'Тохой хэт гадагш. Бэлхүүсээ унжуулах.', easy:'Хана түшиж', hard:'Хөл өндөрт тавих'},
  {id:'superman', n:'Superman', e:'🦸', loc:'home', m:'back', lvl:1, eq:'none', kcal:4, video:'UXUGfiNL1lI', goals:['health','tone'],
    tgt:'Нурууны доод хэсэг, posture', tech:'Гэдсээрээ хэвт. Гар, хөлөө зэрэг дээш өргөж 2 сек барь.',
    err:'Хүзүүгээ хэт буцаах.', easy:'Зөвхөн гар эсвэл хөл', hard:'Удаан барих'},
  {id:'birddog', n:'Bird Dog', e:'🐕', loc:'home', m:'back', lvl:1, eq:'none', kcal:4, video:'ZdAHe9_HeEw', goals:['health','tone'],
    tgt:'Цөм, нуруу, тэнцвэр', tech:'Дөрвөн хөллөж эсрэг гар хөлөө сунгаж 2 сек барь. Ээлжилнэ.',
    err:'Бэлхүүсээ эргүүлэх, өгзгөө доош унжуулах.', easy:'Зөвхөн хөл', hard:'Удаан + резин'},
  {id:'bicycle', n:'Bicycle Crunch', e:'🚲', loc:'home', m:'abs', lvl:1, eq:'none', kcal:6, video:'PAEo-zRSanM', goals:['tone','fatloss'],
    tgt:'Гэдэс, хажуугийн булчин (obliques)', tech:'Нуруугаараа хэвтэж тохойгоо эсрэг өвдөгтэй ойртуул. Дугуй гишгэх хөдөлгөөн.',
    err:'Хүзүүгээ татах. Хэт хурдлах.', easy:'Удаан', hard:'Хөлөө шалнаас доош'},
  {id:'wallsit', n:'Wall Sit (Хана түших суулт)', e:'🧱', loc:'home', m:'legs', lvl:1, eq:'none', kcal:6, video:'JaZNYM3zAP0', goals:['tone','health'],
    tgt:'Гуя, тэсвэр', tech:'Хана түшиж сандал шиг 90° суу. 30–60 сек барь.',
    err:'Өвдөг хурууныхаа чигээс давах.', easy:'Богино барих', hard:'Нэг хөл / удаан'},
  {id:'jjack', n:'Jumping Jack', e:'⭐', loc:'home', m:'cardio', lvl:1, eq:'none', kcal:9, video:'uLVt6u15L98', goals:['fatloss','health'],
    tgt:'Зүрх судас, халаалт', tech:'Үсрэхдээ гар хөлөө зэрэг дэлгэж хаах. Тогтмол хэмнэл.',
    err:'Өвдгөө хатуу газардуулах.', easy:'Алхах хувилбар', hard:'Хурдан tempo'},
  {id:'calf', n:'Calf Raise (Шилбэ)', e:'🦶', loc:'home', m:'legs', lvl:1, eq:'none', kcal:3, video:'k8ipHzKeAkQ', goals:['tone','health'],
    tgt:'Шилбэ (calves)', tech:'Хурууныхаа үзүүр дээр аль болох өндөр гарч 1 сек барь, удаан буулга.',
    err:'Доош унах. Хурдан хийх.', easy:'Хана түшиж', hard:'Нэг хөл дээр'},

  // GYM
  {id:'bench', n:'Bench Press', e:'🏋️', loc:'gym', m:'chest', lvl:2, eq:'barbell', kcal:8, video:'Pp8rHcFVIYg', goals:['muscle','strength'],
    tgt:'Цээж, гарын ар, урд мөр', tech:'Сандал дээр хэвтэж барбеллыг мөрнийхөө дээгүүр барь. Цээж рүүгээ хянаж буулгаад түлх.',
    err:'Өгзгөө сандлаас өргөх. Тохойг хэт дэлгэх.', easy:'Dumbbell press', hard:'Жин нэмэх'},
  {id:'inclinedb', n:'Incline Dumbbell Press', e:'💪', loc:'gym', m:'chest', lvl:2, eq:'dumbbell', kcal:7, video:'sK4Rvug6ufo', goals:['muscle','tone'],
    tgt:'Цээжний дээд хэсэг, мөр', tech:'30–45° налуу сандал дээр гантель түлх. Доод цэгт цээжээ мэдэр.',
    err:'Сандал хэт босоо. Гантель мөргөлдүүлэх.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'latpull', n:'Lat Pulldown', e:'🎯', loc:'gym', m:'back', lvl:1, eq:'cable', kcal:7, video:'-c_TPoSUYuk', goals:['muscle','tone'],
    tgt:'Нурууны өргөн булчин (lats), bicep', tech:'Бариулыг цээж рүүгээ татаж, мөрөө доош, ар руу чангал. Удаан буулга.',
    err:'Их даллах, хүзүүний ард татах.', easy:'Бага жин', hard:'Pull up руу шилжих'},
  {id:'row', n:'Seated Cable Row', e:'🚣', loc:'gym', m:'back', lvl:1, eq:'cable', kcal:7, video:'f_r95UajQcg', goals:['muscle','tone'],
    tgt:'Нурууны дунд, lats, bicep', tech:'Цээжээ өргөж бариулыг гэдэс рүүгээ тат. Мөрөө шахаж 1 сек барь.',
    err:'Нуруугаараа татах, биеэ хэт хойш гозойлгох.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'deadlift', n:'Deadlift', e:'⚡', loc:'gym', m:'back', lvl:3, eq:'barbell', kcal:11, video:'-4qRntuXBSc', goals:['strength','muscle'],
    tgt:'Нуруу, өгзөг, гуяны ар, цөм', tech:'Нуруу шулуун, цээж өргөөстэй. Барбеллыг биедээ ойр хадгалж өгзгөөрөө түлж бос.',
    err:'Нуруугаа дугуйлах — ГЭМТЭХ эрсдэлтэй.', easy:'Romanian DL / бага жин', hard:'Жин нэмэх'},
  {id:'squatbb', n:'Barbell Squat', e:'🏋️‍♀️', loc:'gym', m:'legs', lvl:2, eq:'barbell', kcal:10, video:'8PMjqgR8Wa8', goals:['strength','muscle'],
    tgt:'Гуя, өгзөг, цөм', tech:'Барбелл мөрөн дээр. Цээж өргөж өгзгөө ар руу суулга. Гуя газартай зэрэгцэх хүртэл.',
    err:'Өвдөг дотогш, өсгий салах, цээж унах.', easy:'Goblet squat', hard:'Жин/гүн нэмэх'},
  {id:'legpress', n:'Leg Press', e:'🦿', loc:'gym', m:'legs', lvl:1, eq:'machine', kcal:8, video:'8nm863C0c60', goals:['muscle','tone'],
    tgt:'Гуя, өгзөг', tech:'Хөлөө мөрний өргөнтэй платформ дээр тавь. Өвдгөө 90° хүртэл нугалж түлх.',
    err:'Өвдгөө бүрэн "цоожлох". Өгзөг суудлаас өргөгдөх.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'rdl', n:'Romanian Deadlift', e:'🔗', loc:'gym', m:'glutes', lvl:2, eq:'barbell', kcal:8, video:'aa57T45iFSE', goals:['strength','muscle'],
    tgt:'Гуяны ар (hamstring), өгзөг', tech:'Өвдгөө бага зэрэг нугалж, өгзгөө ар руу түлж жинг доош буулга. Нуруу шулуун.',
    err:'Нуруу дугуйлах. Өвдгөө хэт нугалах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'hipthrust', n:'Hip Thrust', e:'🍑', loc:'gym', m:'glutes', lvl:1, eq:'barbell', kcal:7, video:'S_uZP4UH6J0', goals:['muscle','tone'],
    tgt:'Өгзөг', tech:'Нуруугаа сандалд түшүүлж барбеллыг аарцан дээр тавь. Өгзгөө чангалж дээш түлх.',
    err:'Бэлхүүсээр хотойх. Богино хүрээтэй хийх.', easy:'Bodyweight bridge', hard:'Жин нэмэх'},
  {id:'ohp', n:'Shoulder Press', e:'🙌', loc:'gym', m:'shoulders', lvl:2, eq:'dumbbell', kcal:7, video:'vlFGTI5JzjI', goals:['strength','muscle'],
    tgt:'Мөр (delts), гарын ар', tech:'Гантелийг мөрнөөсөө толгойныхоо дээш түлж бүрэн сунга. Цөмөө чангал.',
    err:'Нуруугаа хойш хотойлгох.', easy:'Бага жин / сууж', hard:'Жин нэмэх'},
  {id:'latraise', n:'Lateral Raise', e:'🪽', loc:'gym', m:'shoulders', lvl:1, eq:'dumbbell', kcal:5, video:'Y29xKcze8Ik', goals:['tone','muscle'],
    tgt:'Мөрний хажуу хэсэг', tech:'Гантелийг хажуу тийш мөрний түвшинд өргө. Тохой бага зэрэг нугалаастай.',
    err:'Их жин аваад биеэ найгуулах.', easy:'Бага жин', hard:'Удаан tempo'},
  {id:'curl', n:'Bicep Curl', e:'💪', loc:'gym', m:'arms', lvl:1, eq:'dumbbell', kcal:5, video:'6DeLZ6cbgWQ', goals:['tone','muscle'],
    tgt:'Гарын урд (biceps)', tech:'Тохойгоо хажуудаа тогтоож гантелийг дээш эргүүлж өргө. Удаан буулга.',
    err:'Биеэ найгуулах, тохой урагшлах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'pushdown', n:'Tricep Pushdown', e:'🔻', loc:'gym', m:'arms', lvl:1, eq:'cable', kcal:5, video:'qHDrQglWgS4', goals:['tone','muscle'],
    tgt:'Гарын ар (triceps)', tech:'Тохойгоо хажуудаа тогтоож бариулыг доош бүрэн түлх.',
    err:'Тохой урагшлах, биеэ налуулах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'cablecr', n:'Cable Crunch', e:'🪢', loc:'gym', m:'abs', lvl:2, eq:'cable', kcal:6, video:'809A_MuZ2PY', goals:['tone','fatloss'],
    tgt:'Гэдэс', tech:'Өвдөглөж, олсыг толгойны хажууд барь. Гэдсээрээ нугалж доош татах.',
    err:'Гараараа татах. Өгзгөө ашиглах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'pullup', n:'Pull Up', e:'🆙', loc:'gym', m:'back', lvl:3, eq:'machine', kcal:9, video:'yl_owH54iH0', goals:['strength','muscle'],
    tgt:'Нуруу (lats), bicep', tech:'Бариулыг мөрнөөс өргөн барь. Цээжээ бариул руу татах хүртэл өргө.',
    err:'Хагас хүрээтэй, найгах.', easy:'Assisted / lat pulldown', hard:'Жин нэмэх'},
  {id:'kneepu', n:'Knee Push Up (Өвдөг дээрх шахалт)', e:'🤸', loc:'home', m:'chest', lvl:1, eq:'none', kcal:5, video:'', goals:['muscle','tone'],
    tgt:'Цээж, мөр, гарын ар', tech:'Өвдөг дээрээ тулж, өвдгөөс мөр хүртэл бие шулуун байлга. Цээжээ доош буулгаад дээш түлх. Өгзгөө бүү дээш өргө.',
    err:'Өгзөг дээш өргөгдөх, бэлхүүс унжих. Хагас буух.', easy:'Хана түшсэн push-up', hard:'Стандарт push-up'},
  {id:'incpu', n:'Incline Push Up (Налуу шахалт)', e:'📐', loc:'home', m:'chest', lvl:1, eq:'none', kcal:5, video:'', goals:['muscle','tone'],
    tgt:'Цээжний дээд хэсэг, мөр', tech:'Гараа ширээ, сандал эсвэл хананд тулга. Бие толгойноос өсгий хүртэл шулуун. Цээжээ тулгуур руу буулгаад түлх.',
    err:'Өгзөг дээш өргөгдөх. Тулгуур тогтворгүй байх.', easy:'Илүү өндөр тулгуур (хана)', hard:'Намхан тулгуур / стандарт push-up'},
  {id:'declpu', n:'Decline Push Up (Хөл өндөрт шахалт)', e:'⛰️', loc:'home', m:'chest', lvl:2, eq:'none', kcal:8, video:'', goals:['muscle','strength'],
    tgt:'Цээжний дээд хэсэг, мөр, гарын ар', tech:'Хөлөө сандал эсвэл буйдан дээр тавь. Бие шулуун. Цээжээ шалан дээр буулгаад дээш түлх.',
    err:'Бэлхүүс хотойх. Хүзүүгээ хугалж доош харах.', easy:'Стандарт push-up', hard:'Хөлөө илүү өндөрт тавих'},
  {id:'diamondpu', n:'Diamond Push Up (Алмаз шахалт)', e:'💎', loc:'home', m:'arms', lvl:2, eq:'none', kcal:7, video:'', goals:['muscle','strength'],
    tgt:'Гарын ар (triceps), цээж', tech:'Хоёр гарын эрхий, долоовор хуруугаа нийлүүлж алмаз хэлбэр үүсгэ. Тохойгоо биедээ ойр нугалж цээжээ гар руугаа буулга.',
    err:'Тохой хажуу тийш дэлгэгдэх. Өгзөг дээш өргөгдөх.', easy:'Өвдөг дээрх diamond push-up', hard:'Хөл өндөрт diamond push-up'},
  {id:'sumosquat', n:'Sumo Squat (Өргөн суулт)', e:'🤼', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'', goals:['tone','fatloss','muscle'],
    tgt:'Гуяны дотор тал, өгзөг', tech:'Хөлөө мөрнөөс өргөн, хурууны үзүүрээ гадагш 30–45° харуул. Өвдгөө хурууныхаа чигт дагуулж доош суу.',
    err:'Өвдөг дотогш орох. Цээж урагш унах.', easy:'Хагас гүнтэй суулт', hard:'Гантель барьж хийх'},
  {id:'jumpsquat', n:'Jump Squat (Үсрэх суулт)', e:'⚡', loc:'home', m:'legs', lvl:2, eq:'none', kcal:11, video:'', goals:['fatloss','strength'],
    tgt:'Гуя, өгзөг, тэсрэх хүч', tech:'Суулт хийгээд дээш хүчтэй үсэр. Өвдгөө зөөлөн нугалж чимээгүй газардаад дараагийн давталтаа үргэлжлүүл.',
    err:'Шулуун хөл дээр газардах. Өвдөг дотогш орох.', easy:'Энгийн суулт', hard:'Үргэлжилсэн хурдтай давталт'},
  {id:'splitsquat', n:'Bulgarian Split Squat (Булгар суулт)', e:'🦶', loc:'home', m:'legs', lvl:2, eq:'none', kcal:9, video:'', goals:['muscle','strength','tone'],
    tgt:'Нэг хөлний гуя, өгзөг, тэнцвэр', tech:'Хойд хөлөө сандал дээр тавь. Урд хөл дээрээ доош суугаад өсгийгөөрөө түлхэж бос. Бие босоо.',
    err:'Урд хөл хэт ойр — өвдөг хэт давах. Бие хажуу тийш хазайх.', easy:'Барьц барьж хийх', hard:'Гантель барих'},
  {id:'revlunge', n:'Reverse Lunge (Ухрах алхалт)', e:'↩️', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'', goals:['tone','fatloss'],
    tgt:'Гуя, өгзөг, тэнцвэр', tech:'Нэг хөлөөрөө ухарч алхаад хойд өвдгөө газар руу буулга. Урд өсгийгөөрөө түлхэж анхны байрлалдаа буц.',
    err:'Хэт богино алхах. Бие урагш унах.', easy:'Барьц барьж хийх', hard:'Гантель барих'},
  {id:'stepup', n:'Step Up (Шат өөд алхалт)', e:'🪜', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'', goals:['tone','fatloss','health'],
    tgt:'Гуя, өгзөг', tech:'Бат бөх сандал эсвэл шатан дээр нэг хөлөө тавь. Өсгийгөөрөө түлхэж бүрэн бос, дараа нь хяналттай буу.',
    err:'Доод хөлөөрөө түлхэх. Хэт өндөр тавцан сонгох.', easy:'Намхан тавцан', hard:'Өндөр тавцан / гантель'},
  {id:'sglute', n:'Single-leg Glute Bridge (Нэг хөлт гүүр)', e:'🦩', loc:'home', m:'glutes', lvl:2, eq:'none', kcal:6, video:'', goals:['tone','muscle'],
    tgt:'Өгзөг, гуяны ар', tech:'Нуруугаараа хэвтэж нэг хөлөө дээш сунга. Тулж буй өсгийгөөрөө түлхэж аарцгаа өргөөд дээд цэгт өгзгөө чангал.',
    err:'Аарцаг нэг тал руугаа хазайх. Бэлхүүсээр хотойх.', easy:'Хоёр хөлт гүүр', hard:'Мөрөө сандал дээр тавих'},
  {id:'donkey', n:'Donkey Kick (Өгзөгний өшиглөлт)', e:'🐴', loc:'home', m:'glutes', lvl:1, eq:'none', kcal:5, video:'', goals:['tone','health'],
    tgt:'Өгзөг', tech:'Дөрвөн хөндлөн байрлалд ор. Өвдгөө 90° нугалсан хэвээр нэг хөлөө дээш өшиглө. Өгзгөө чангалж буцааж буулга.',
    err:'Бэлхүүсээр хотойх. Хэт өндөр өргөх.', easy:'Хүрээг багасгах', hard:'Резинтэй хийх'},
  {id:'sideplank', n:'Side Plank (Хажуугийн тэвш)', e:'📏', loc:'home', m:'abs', lvl:2, eq:'none', kcal:4, video:'', goals:['tone','health'],
    tgt:'Хажуугийн булчин (obliques), цөм', tech:'Хажуугаараа хэвтэж тохойгоо мөрнийхөө доор тул. Аарцгаа дээш өргөж толгойноос өсгий хүртэл шулуун барь. 20–45 сек.',
    err:'Аарцаг унжих. Мөр тохойноос урагш гарах.', easy:'Өвдөг дээрээ хийх', hard:'Дээд хөлөө өргөх'},
  {id:'deadbug', n:'Dead Bug (Цох хөдөлгөөн)', e:'🪲', loc:'home', m:'abs', lvl:1, eq:'none', kcal:4, video:'', goals:['tone','health'],
    tgt:'Гүний цөм, бэлхүүсийн тогтвор', tech:'Нуруугаараа хэвтэж гар, өвдгөө дээш өргө. Эсрэг гар, хөлөө удаанаар сунгаад буцаа. Бэлхүүс шалнаас салахгүй.',
    err:'Бэлхүүс шалнаас салж хотойх. Хэт хурдан хийх.', easy:'Зөвхөн хөл сунгах', hard:'Хүрээг уртасгах'},
  {id:'crunch', n:'Crunch (Гэдэсний атгалт)', e:'🔽', loc:'home', m:'abs', lvl:1, eq:'none', kcal:5, video:'', goals:['tone','fatloss'],
    tgt:'Гэдэсний шулуун булчин', tech:'Нуруугаараа хэвтэж өвдгөө нугал. Мөрөө шалнаас хөндийлгөж гэдсээрээ атга, дараа нь хяналттай буу.',
    err:'Хүзүүгээ гараараа татах. Хэт хурдан савлах.', easy:'Хүрээг багасгах', hard:'Гараа толгой дээгүүрээ сунгах'},
  {id:'legraise', n:'Lying Leg Raise (Хэвтээ хөл өргөлт)', e:'🦵', loc:'home', m:'abs', lvl:2, eq:'none', kcal:5, video:'', goals:['tone','muscle'],
    tgt:'Гэдэсний доод хэсэг', tech:'Нуруугаараа хэвтэж хөлөө хамтад нь шулуун өргө. Бэлхүүсээ шалан дээр наалдуулсан хэвээр удаанаар буулга.',
    err:'Бэлхүүс хотойх. Хөлөө шалан дээр унагах.', easy:'Өвдгөө нугалж хийх', hard:'Хөлөө шалнаас хөндийлгөж барих'},
  {id:'hollow', n:'Hollow Hold (Хотгор барилт)', e:'🌙', loc:'home', m:'abs', lvl:2, eq:'none', kcal:5, video:'', goals:['tone','strength'],
    tgt:'Цөм бүхэлдээ', tech:'Нуруугаараа хэвтэж гар, хөлөө шалнаас хөндийлгө. Бэлхүүсээ шалан дээр дарж завь хэлбэртэй 15–40 сек барь.',
    err:'Бэлхүүс шалнаас салах. Амьсгалаа барих.', easy:'Өвдгөө нугалж барих', hard:'Гараа толгой дээгүүрээ сунгах'},
  {id:'russian', n:'Russian Twist (Оросын эргэлт)', e:'🔄', loc:'home', m:'abs', lvl:2, eq:'none', kcal:6, video:'', goals:['tone','fatloss'],
    tgt:'Хажуугийн булчин (obliques)', tech:'Суугаад бие бага зэрэг хойш налуу, хөлөө хөндийлгө. Гараа хоёр тийш ээлжлэн эргүүлж цөмөөрөө хянана.',
    err:'Зөвхөн гараа савлах. Нуруугаар бөхийх.', easy:'Хөлөө газар дээр тавих', hard:'Жин барих'},
  {id:'highknees', n:'High Knees (Өндөр өвдөг)', e:'🏃', loc:'home', m:'cardio', lvl:1, eq:'none', kcal:11, video:'', goals:['fatloss','health'],
    tgt:'Зүрх судас, хөл, цөм', tech:'Байрандаа гүйж өвдгөө аарцгийн түвшинд өргө. Хөлийн өлмийгөөр зөөлөн газарда, гараа хөдөлгө.',
    err:'Өвдөг хангалтгүй өндөр. Өсгий дээр хүчтэй газардах.', easy:'Байрандаа алхах', hard:'Хурдаа нэмэх'},
  {id:'skater', n:'Skater Jump (Тэшүүрийн үсрэлт)', e:'⛸️', loc:'home', m:'cardio', lvl:2, eq:'none', kcal:11, video:'', goals:['fatloss','strength'],
    tgt:'Зүрх судас, хөл, тэнцвэр', tech:'Нэг талдаа хажуу тийш үсэрч нөгөө хөлөө ар хөндлөн гүйцээ. Зөөлөн газардаж тэнцвэрээ барь, дараа нь нөгөө тал руу.',
    err:'Хатуу газардах. Өвдөг дотогш орох.', easy:'Үсрэхгүй хажуу алхалт', hard:'Үсрэлтийн зайг уртасгах'},
  {id:'benchdip', n:'Bench Dip (Сандал түшсэн dip)', e:'🪑', loc:'home', m:'arms', lvl:1, eq:'none', kcal:6, video:'', goals:['muscle','tone'],
    tgt:'Гарын ар (triceps), мөр', tech:'Сандлын ирмэг дээр гараа тавь. Өгзгөө ирмэгээс урагшлуулж тохойгоо 90° хүртэл нугалаад дээш түлх.',
    err:'Мөрөө чихэндээ ойртуулах. Хагас буух.', easy:'Өвдгөө нугалж хийх', hard:'Хөлөө шулуун сунгах'},
  {id:'inclinebb', n:'Incline Barbell Press (Налуу barbell түлхэлт)', e:'📈', loc:'gym', m:'chest', lvl:2, eq:'barbell', kcal:9, video:'', goals:['muscle','strength'],
    tgt:'Цээжний дээд хэсэг, мөр, гарын ар', tech:'Вандан сандлыг 30–45° налуулж хэвт. Штангийг цээжний дээд хэсэгт буулгаад дээш түлх. Бугуй шулуун.',
    err:'Хэт эгц налуу — мөрөнд ачаалал. Штангийг цээжнээс үсрүүлэх.', easy:'Гантелийн налуу түлхэлт', hard:'Жин нэмэх'},
  {id:'chestpress', n:'Machine Chest Press (Машин дээрх цээжний түлхэлт)', e:'🏗️', loc:'gym', m:'chest', lvl:1, eq:'machine', kcal:7, video:'', goals:['muscle','tone'],
    tgt:'Цээж, мөр, гарын ар', tech:'Суудлыг бариул цээжний түвшинд таарахаар тохируул. Нуруугаа түшлэгт нааж урагш түлхээд хяналттай буцаа.',
    err:'Суудлын өндөр буруу. Тохойг бүрэн цоожлох.', easy:'Жинг багасгах', hard:'Жин нэмэх / удаан буцаах'},
  {id:'dbfly', n:'Dumbbell Fly (Гантелийн нээлт)', e:'🦋', loc:'gym', m:'chest', lvl:2, eq:'dumbbell', kcal:7, video:'', goals:['muscle','tone'],
    tgt:'Цээж (сунгалт)', tech:'Вандан дээр хэвтэж гантелийг цээжний дээр барь. Тохойгоо бага зэрэг нугалсан хэвээр хоёр тийш нээгээд цээжээрээ татан хааж ир.',
    err:'Тохойгоо шулуун барих. Хэт гүн нээх.', easy:'Хөнгөн жин, бага хүрээ', hard:'Удаан тэмпо'},
  {id:'seatedrow', n:'Seated Cable Row (Суугаа cable row)', e:'🚣', loc:'gym', m:'back', lvl:1, eq:'cable', kcal:8, video:'', goals:['muscle','strength','tone'],
    tgt:'Нурууны дунд хэсэг, bicep', tech:'Суугаад өвдгөө бага зэрэг нугал. Бариулыг гэдэс рүүгээ татаж мөрний ясаа нийлүүл, дараа нь хяналттай сунга.',
    err:'Биеэрээ савлах. Мөрөө дээш өргөх.', easy:'Хөнгөн жин', hard:'Жин нэмэх / дээд цэгт 1 сек барих'},
  {id:'dbrow', n:'One-arm Dumbbell Row (Нэг гарын гантель row)', e:'🪝', loc:'gym', m:'back', lvl:1, eq:'dumbbell', kcal:8, video:'', goals:['muscle','strength'],
    tgt:'Нурууны өргөн булчин (lats)', tech:'Нэг өвдөг, гараа вандан дээр тул. Гантелийг аарцаг руугаа татаж тохойгоо хойш чиглүүл, дараа нь хяналттай буулга.',
    err:'Биеэ эргүүлж татах. Нуруугаар бөхийх.', easy:'Хөнгөн жин', hard:'Жин нэмэх / удаан буулгах'},
  {id:'facepull', n:'Face Pull (Нүүр рүү татах)', e:'🎯', loc:'gym', m:'shoulders', lvl:1, eq:'cable', kcal:6, video:'', goals:['health','tone','muscle'],
    tgt:'Мөрний ар, нурууны дээд хэсэг', tech:'Олсон бариулыг нүүрнийхээ түвшинд тохируул. Тохойгоо өндөр байлган нүүр рүүгээ татаж мөрний ясаа нийлүүл.',
    err:'Хэт хүнд жин — биеэрээ татах. Тохой доош унах.', easy:'Хөнгөн жин', hard:'Дээд цэгт 2 сек барих'},
  {id:'dbpress', n:'Seated Dumbbell Press (Суугаа гантелийн түлхэлт)', e:'🪖', loc:'gym', m:'shoulders', lvl:1, eq:'dumbbell', kcal:8, video:'', goals:['muscle','strength'],
    tgt:'Мөр, гарын ар', tech:'Түшлэгтэй сандал дээр суу. Гантелийг чихний түвшнээс дээш түлхэж бүрэн тэнийлгээд хяналттай буулга.',
    err:'Бэлхүүсээр хотойх. Хагас буулгах.', easy:'Хөнгөн жин', hard:'Зогсож хийх / жин нэмэх'},
  {id:'rearfly', n:'Rear Delt Fly (Мөрний арын нээлт)', e:'🕊️', loc:'gym', m:'shoulders', lvl:2, eq:'dumbbell', kcal:6, video:'', goals:['tone','muscle','health'],
    tgt:'Мөрний ар, нурууны дээд хэсэг', tech:'Аарцгаасаа бөхийж нуруугаа шулуун барь. Хөнгөн гантелийг хоёр тийш далавч шиг өргөөд хяналттай буулга.',
    err:'Хэт хүнд жин — биеэрээ савлах. Нуруугаар бөхийх.', easy:'Вандан дээр цээжээрээ тулж хийх', hard:'Дээд цэгт 2 сек барих'},
  {id:'legext', n:'Leg Extension (Хөлний сунгалт)', e:'🦿', loc:'gym', m:'legs', lvl:1, eq:'machine', kcal:7, video:'', goals:['muscle','tone'],
    tgt:'Гуяны урд (quads)', tech:'Суудал, дэрний байрлалыг тохируул. Хөлөө шулуун сунгаж дээд цэгт 1 сек барь, дараа нь хяналттай буулга.',
    err:'Жинг хурдан буцаах. Өгзгөө суудлаас өргөх.', easy:'Хөнгөн жин', hard:'Удаан буулгах / жин нэмэх'},
  {id:'legcurl', n:'Leg Curl (Гуяны арын нугалалт)', e:'🔧', loc:'gym', m:'legs', lvl:1, eq:'machine', kcal:7, video:'', goals:['muscle','tone','health'],
    tgt:'Гуяны ар (hamstrings)', tech:'Дэрийг шилбэний доод хэсэгт тохируул. Өсгийгөөрөө нугалж татаад хяналттай буцаа.',
    err:'Аарцгаа дээш өргөх. Хагас хүрээтэй хийх.', easy:'Хөнгөн жин', hard:'Удаан буцаах / жин нэмэх'},
  {id:'hammer', n:'Hammer Curl (Алхны curl)', e:'🔨', loc:'gym', m:'arms', lvl:1, eq:'dumbbell', kcal:6, video:'', goals:['muscle','tone'],
    tgt:'Bicep, шууны булчин', tech:'Гантелийг эрхий дээш харуулсан голч атгалтаар барь. Тохойгоо хажуудаа тогтоож дээш татаад удаан буулга.',
    err:'Биеэрээ савлах. Тохой урагш гарах.', easy:'Хөнгөн жин', hard:'Нэг нэгээр нь удаан хийх'},
];

/* ---------- copy ---------- */
const GOALS = [
  {id:'fatloss', n:'Жин хасах', e:'🔥'},
  {id:'muscle',  n:'Булчин нэмэх', e:'💪'},
  {id:'tone',    n:'Бие чангалах', e:'✨'},
  {id:'strength',n:'Хүч нэмэх', e:'⚡'},
  {id:'health',  n:'Эрүүл амьдрал', e:'🌿'},
];
const goalName = id => (GOALS.find(g=>g.id===id)||{}).n || '';
const M_NAMES = {chest:'Цээж', back:'Нуруу', legs:'Хөл', glutes:'Өгзөг', shoulders:'Мөр', arms:'Гар', abs:'Гэдэс', cardio:'Кардио'};
const LVL_NAMES = {1:'Анхан', 2:'Дунд', 3:'Ахисан'};
