/* ---------- exercise database (Монгол) ---------- */
// loc: 'home' | 'gym'   m: muscle group   lvl: 1 beg /2 int /3 adv   eq: equipment tag
// goals: this exercise fits which goal filters ('fatloss'|'muscle'|'tone'|'strength'|'health')
// video: YouTube video id ('' = none yet) — see js/views/exercise.js videoEmbed()
const EX = [
  // HOME — bodyweight
  {id:'pushup', n:'Push Up (Шахалт)', e:'🤸', loc:'home', m:'chest', lvl:1, eq:'none', kcal:7, video:'WDIpL0pjun0', goals:['muscle','tone','strength'],
    tgt:'Цээж, мөр, гарын ар (triceps)', tech:'Гараа мөрнөөсөө бага зэрэг өргөн тавь. Бие шулуун — толгойноос өсгий хүртэл нэг шугам. Цээжээ доош буулгаад дээш түлх.',
    err:'Нуруугаа хотойлгох, өгзгөө дээш өргөх. Толгойгоо унжуулах.', easy:'Өвдөг дээрээ push up', hard:'Decline (хөл өндөрт)'},
  {id:'squat', n:'Bodyweight Squat (Суулт)', e:'🦵', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'DlS-GAF8Edg', goals:['muscle','tone','fatloss'],
    tgt:'Гуя (quads), өгзөг', tech:'Хөлөө мөрний өргөнтэй тавь. Өгзгөө ар руу суулгаж, цээжээ өргөж, өвдгөө хурууныхаа чигт чиглүүл.',
    err:'Өвдөг дотогшоо орох, өсгий газраас салах.', easy:'Сандал руу суух', hard:'Jump squat'},
  {id:'lunge', n:'Lunge (Урагшаа алхалт)', e:'🚶', loc:'home', m:'legs', lvl:1, eq:'none', kcal:8, video:'g8-Ge9S0aUw', goals:['tone','fatloss'],
    tgt:'Гуя, өгзөг, тэнцвэр', tech:'Урагшаа том алхаад хойд өвдгөө газар руу буулга. Хоёр өвдөг 90°. Өсгийгөөрөө түлхэж буц.',
    err:'Урд өвдөг хурууныхаа чигээс хэт давах.', easy:'Барьц барьж хийх', hard:'Walking lunge / гантельтэй'},
  {id:'glute', n:'Glute Bridge (Өгзгийн гүүр)', e:'🍑', loc:'home', m:'glutes', lvl:1, eq:'none', kcal:5, video:'wPM8icPu6H8', goals:['tone','muscle'],
    tgt:'Өгзөг, гуяны ар', tech:'Нуруугаараа хэвт, өвдгөө нугал. Өгзгөө чангалж аарцгаа дээш өргө. Дээд цэгт 1 сек барь.',
    err:'Бэлхүүсээрээ хотойх. Өгзгөө чангалахгүй байх.', easy:'—', hard:'Нэг хөл дээр'},
  {id:'plank', n:'Plank (Тэвш)', e:'🧘', loc:'home', m:'abs', lvl:1, eq:'none', kcal:4, video:'mwlp75MS6Rg', goals:['tone','health'],
    tgt:'Гэдэс, цөм (core)', tech:'Тохой мөрнийхөө доор. Бие шулуун. Гэдэс, өгзгөө чангал. 20–60 сек барь.',
    err:'Өгзөг дээш/доош, нуруу унжих.', easy:'Өвдөг дээр', hard:'Plank + хөл өргөх'},
  {id:'mtclimb', n:'Mountain Climber', e:'⛰️', loc:'home', m:'abs', lvl:2, eq:'none', kcal:11, video:'ixxk9Qfn61o', goals:['fatloss','health'],
    tgt:'Гэдэс, мөр, зүрх судас', tech:'Plank байрлалаас өвдгөө ээлжлэн цээж рүүгээ хурдан татаж ир. Өгзгөө тэгш барь.',
    err:'Өгзгөө дээш өргөх, хурдыг техникээс түрүүлүүлэх.', easy:'Удаан хийх', hard:'Cross-body хувилбар'},
  {id:'burpee', n:'Burpee', e:'🔥', loc:'home', m:'cardio', lvl:2, eq:'none', kcal:14, video:'wGvBfVeCNko', goals:['fatloss','health'],
    tgt:'Бүх бие, зүрх судас, өөх шатаалт', tech:'Суугаад гараа тавьж, хөлөө ухасхийн plank болж, буцааж татаад дээш үсэр.',
    err:'Нуруу хотойх. Хэт хурдлаад техник алдах.', easy:'Үсрэлтгүй', hard:'Push up нэмэх'},
  {id:'pikepu', n:'Pike Push Up', e:'🔺', loc:'home', m:'shoulders', lvl:2, eq:'none', kcal:7, video:'pHR5yG6xBps', goals:['muscle','tone'],
    tgt:'Мөр (delts), гарын ар', tech:'Өгзгөө дээш өргөж "А" хэлбэр үүсгэ. Толгойгоо газар руу буулгаж дээш түлх.',
    err:'Тохой хэт гадагш. Бэлхүүсээ унжуулах.', easy:'Хана түшиж', hard:'Хөл өндөрт тавих'},
  {id:'superman', n:'Superman', e:'🦸', loc:'home', m:'back', lvl:1, eq:'none', kcal:4, video:'UXUGfiNL1lI', goals:['health','tone'],
    tgt:'Нурууны доод хэсэг, posture', tech:'Гэдсээрээ хэвт. Гар, хөлөө зэрэг дээш өргөж 2 сек барь.',
    err:'Хүзүүгээ хэт буцаах.', easy:'Зөвхөн гар эсвэл хөл', hard:'Удаан барих'},
  {id:'birddog', n:'Bird Dog', e:'🐕', loc:'home', m:'back', lvl:1, eq:'none', kcal:4, video:'ZdAHe9_HeEw', goals:['health','tone'],
    tgt:'Цөм, нуруу, тэнцвэр', tech:'Дөрвөн хөллөж эсрэг гар хөлөө сунгаж 2 сек барь. Ээлжилнэ.',
    err:'Бэлхүүсээ эргүүлэх, өгзгөө доош унжуулах.', easy:'Зөвхөн хөл', hard:'Удаан + резин'},
  {id:'bicycle', n:'Bicycle Crunch', e:'🚲', loc:'home', m:'abs', lvl:1, eq:'none', kcal:6, video:'PAEo-zRSanM', goals:['tone','fatloss'],
    tgt:'Гэдэс, хажуугийн булчин (obliques)', tech:'Нуруугаараа хэвтэж тохойгоо эсрэг өвдөгтэй ойртуул. Дугуй гишгэх хөдөлгөөн.',
    err:'Хүзүүгээ татах. Хэт хурдлах.', easy:'Удаан', hard:'Хөлөө шалнаас доош'},
  {id:'wallsit', n:'Wall Sit (Хана түших суулт)', e:'🧱', loc:'home', m:'legs', lvl:1, eq:'none', kcal:6, video:'JaZNYM3zAP0', goals:['tone','health'],
    tgt:'Гуя, тэсвэр', tech:'Хана түшиж сандал шиг 90° суу. 30–60 сек барь.',
    err:'Өвдөг хурууныхаа чигээс давах.', easy:'Богино барих', hard:'Нэг хөл / удаан'},
  {id:'jjack', n:'Jumping Jack', e:'⭐', loc:'home', m:'cardio', lvl:1, eq:'none', kcal:9, video:'uLVt6u15L98', goals:['fatloss','health'],
    tgt:'Зүрх судас, халаалт', tech:'Үсрэхдээ гар хөлөө зэрэг дэлгэж хаах. Тогтмол хэмнэл.',
    err:'Өвдгөө хатуу газардуулах.', easy:'Алхах хувилбар', hard:'Хурдан tempo'},
  {id:'calf', n:'Calf Raise (Шилбэ)', e:'🦶', loc:'home', m:'legs', lvl:1, eq:'none', kcal:3, video:'k8ipHzKeAkQ', goals:['tone','health'],
    tgt:'Шилбэ (calves)', tech:'Хурууныхаа үзүүр дээр аль болох өндөр гарч 1 сек барь, удаан буулга.',
    err:'Доош унах. Хурдан хийх.', easy:'Хана түшиж', hard:'Нэг хөл дээр'},

  // GYM
  {id:'bench', n:'Bench Press', e:'🏋️', loc:'gym', m:'chest', lvl:2, eq:'barbell', kcal:8, video:'Pp8rHcFVIYg', goals:['muscle','strength'],
    tgt:'Цээж, гарын ар, урд мөр', tech:'Сандал дээр хэвтэж барбеллыг мөрнийхөө дээгүүр барь. Цээж рүүгээ хянаж буулгаад түлх.',
    err:'Өгзгөө сандлаас өргөх. Тохойг хэт дэлгэх.', easy:'Dumbbell press', hard:'Жин нэмэх'},
  {id:'inclinedb', n:'Incline Dumbbell Press', e:'💪', loc:'gym', m:'chest', lvl:2, eq:'dumbbell', kcal:7, video:'sK4Rvug6ufo', goals:['muscle','tone'],
    tgt:'Цээжний дээд хэсэг, мөр', tech:'30–45° налуу сандал дээр гантель түлх. Доод цэгт цээжээ мэдэр.',
    err:'Сандал хэт босоо. Гантель мөргөлдүүлэх.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'latpull', n:'Lat Pulldown', e:'🎯', loc:'gym', m:'back', lvl:1, eq:'cable', kcal:7, video:'-c_TPoSUYuk', goals:['muscle','tone'],
    tgt:'Нурууны өргөн булчин (lats), bicep', tech:'Бариулыг цээж рүүгээ татаж, мөрөө доош, ар руу чангал. Удаан буулга.',
    err:'Их даллах, хүзүүний ард татах.', easy:'Бага жин', hard:'Pull up руу шилжих'},
  {id:'row', n:'Seated Cable Row', e:'🚣', loc:'gym', m:'back', lvl:1, eq:'cable', kcal:7, video:'f_r95UajQcg', goals:['muscle','tone'],
    tgt:'Нурууны дунд, lats, bicep', tech:'Цээжээ өргөж бариулыг гэдэс рүүгээ тат. Мөрөө шахаж 1 сек барь.',
    err:'Нуруугаараа татах, биеэ хэт хойш гозойлгох.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'deadlift', n:'Deadlift', e:'⚡', loc:'gym', m:'back', lvl:3, eq:'barbell', kcal:11, video:'-4qRntuXBSc', goals:['strength','muscle'],
    tgt:'Нуруу, өгзөг, гуяны ар, цөм', tech:'Нуруу шулуун, цээж өргөөстэй. Барбеллыг биедээ ойр хадгалж өгзгөөрөө түлж бос.',
    err:'Нуруугаа дугуйлах — ГЭМТЭХ эрсдэлтэй.', easy:'Romanian DL / бага жин', hard:'Жин нэмэх'},
  {id:'squatbb', n:'Barbell Squat', e:'🏋️‍♀️', loc:'gym', m:'legs', lvl:2, eq:'barbell', kcal:10, video:'8PMjqgR8Wa8', goals:['strength','muscle'],
    tgt:'Гуя, өгзөг, цөм', tech:'Барбелл мөрөн дээр. Цээж өргөж өгзгөө ар руу суулга. Гуя газартай зэрэгцэх хүртэл.',
    err:'Өвдөг дотогш, өсгий салах, цээж унах.', easy:'Goblet squat', hard:'Жин/гүн нэмэх'},
  {id:'legpress', n:'Leg Press', e:'🦿', loc:'gym', m:'legs', lvl:1, eq:'machine', kcal:8, video:'8nm863C0c60', goals:['muscle','tone'],
    tgt:'Гуя, өгзөг', tech:'Хөлөө мөрний өргөнтэй платформ дээр тавь. Өвдгөө 90° хүртэл нугалж түлх.',
    err:'Өвдгөө бүрэн "цоожлох". Өгзөг суудлаас өргөгдөх.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'rdl', n:'Romanian Deadlift', e:'🔗', loc:'gym', m:'glutes', lvl:2, eq:'barbell', kcal:8, video:'aa57T45iFSE', goals:['strength','muscle'],
    tgt:'Гуяны ар (hamstring), өгзөг', tech:'Өвдгөө бага зэрэг нугалж, өгзгөө ар руу түлж жинг доош буулга. Нуруу шулуун.',
    err:'Нуруу дугуйлах. Өвдгөө хэт нугалах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'hipthrust', n:'Hip Thrust', e:'🍑', loc:'gym', m:'glutes', lvl:1, eq:'barbell', kcal:7, video:'S_uZP4UH6J0', goals:['muscle','tone'],
    tgt:'Өгзөг', tech:'Нуруугаа сандалд түшүүлж барбеллыг аарцан дээр тавь. Өгзгөө чангалж дээш түлх.',
    err:'Бэлхүүсээр хотойх. Богино хүрээтэй хийх.', easy:'Bodyweight bridge', hard:'Жин нэмэх'},
  {id:'ohp', n:'Shoulder Press', e:'🙌', loc:'gym', m:'shoulders', lvl:2, eq:'dumbbell', kcal:7, video:'vlFGTI5JzjI', goals:['strength','muscle'],
    tgt:'Мөр (delts), гарын ар', tech:'Гантелийг мөрнөөсөө толгойныхоо дээш түлж бүрэн сунга. Цөмөө чангал.',
    err:'Нуруугаа хойш хотойлгох.', easy:'Бага жин / сууж', hard:'Жин нэмэх'},
  {id:'latraise', n:'Lateral Raise', e:'🪽', loc:'gym', m:'shoulders', lvl:1, eq:'dumbbell', kcal:5, video:'Y29xKcze8Ik', goals:['tone','muscle'],
    tgt:'Мөрний хажуу хэсэг', tech:'Гантелийг хажуу тийш мөрний түвшинд өргө. Тохой бага зэрэг нугалаастай.',
    err:'Их жин аваад биеэ найгуулах.', easy:'Бага жин', hard:'Удаан tempo'},
  {id:'curl', n:'Bicep Curl', e:'💪', loc:'gym', m:'arms', lvl:1, eq:'dumbbell', kcal:5, video:'6DeLZ6cbgWQ', goals:['tone','muscle'],
    tgt:'Гарын урд (biceps)', tech:'Тохойгоо хажуудаа тогтоож гантелийг дээш эргүүлж өргө. Удаан буулга.',
    err:'Биеэ найгуулах, тохой урагшлах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'pushdown', n:'Tricep Pushdown', e:'🔻', loc:'gym', m:'arms', lvl:1, eq:'cable', kcal:5, video:'qHDrQglWgS4', goals:['tone','muscle'],
    tgt:'Гарын ар (triceps)', tech:'Тохойгоо хажуудаа тогтоож бариулыг доош бүрэн түлх.',
    err:'Тохой урагшлах, биеэ налуулах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'cablecr', n:'Cable Crunch', e:'🪢', loc:'gym', m:'abs', lvl:2, eq:'cable', kcal:6, video:'809A_MuZ2PY', goals:['tone','fatloss'],
    tgt:'Гэдэс', tech:'Өвдөглөж, олсыг толгойны хажууд барь. Гэдсээрээ нугалж доош татах.',
    err:'Гараараа татах. Өгзгөө ашиглах.', easy:'Бага жин', hard:'Жин нэмэх'},
  {id:'pullup', n:'Pull Up', e:'🆙', loc:'gym', m:'back', lvl:3, eq:'machine', kcal:9, video:'yl_owH54iH0', goals:['strength','muscle'],
    tgt:'Нуруу (lats), bicep', tech:'Бариулыг мөрнөөс өргөн барь. Цээжээ бариул руу татах хүртэл өргө.',
    err:'Хагас хүрээтэй, найгах.', easy:'Assisted / lat pulldown', hard:'Жин нэмэх'},
];

/* ---------- copy ---------- */
const GOALS = [
  {id:'fatloss', n:'Жин хасах', e:'🔥'},
  {id:'muscle',  n:'Булчин нэмэх', e:'💪'},
  {id:'tone',    n:'Бие чангалах', e:'✨'},
  {id:'strength',n:'Хүч нэмэх', e:'⚡'},
  {id:'health',  n:'Эрүүл амьдрал', e:'🌿'},
];
const goalName = id => (GOALS.find(g=>g.id===id)||{}).n || '';
const M_NAMES = {chest:'Цээж', back:'Нуруу', legs:'Хөл', glutes:'Өгзөг', shoulders:'Мөр', arms:'Гар', abs:'Гэдэс', cardio:'Кардио'};
const LVL_NAMES = {1:'Анхан', 2:'Дунд', 3:'Ахисан'};
