/* ---------- exercise demonstration photos ----------
   Two frames per exercise (start and end of the movement) from the
   free-exercise-db public-domain dataset (Unlicense, https://github.com/yuhonas/free-exercise-db),
   resized and converted to WebP in assets/ex/. Alternating the two frames
   shows the movement. Exercises not listed here have no photo in that
   dataset and keep their drawn muscle figure instead. */
const EX_PHOTOS = {
"bench": 2,
"benchdip": 2,
"bicycle": 2,
"cablecr": 2,
"calf": 2,
"chestpress": 2,
"crunch": 2,
"curl": 2,
"dbfly": 2,
"dbpress": 2,
"dbrow": 2,
"deadbug": 2,
"deadlift": 2,
"declpu": 2,
"diamondpu": 2,
"donkey": 2,
"facepull": 2,
"glute": 2,
"hammer": 2,
"hipthrust": 2,
"inclinebb": 2,
"inclinedb": 2,
"incpu": 2,
"jumpsquat": 2,
"kneepu": 2,
"latpull": 2,
"latraise": 2,
"legcurl": 2,
"legext": 2,
"legpress": 2,
"legraise": 2,
"lunge": 2,
"mtclimb": 2,
"ohp": 2,
"plank": 2,
"pullup": 2,
"pushdown": 2,
"pushup": 2,
"rdl": 2,
"rearfly": 2,
"revlunge": 2,
"row": 2,
"russian": 2,
"seatedrow": 2,
"sglute": 2,
"sideplank": 2,
"skater": 2,
"squat": 2,
"squatbb": 2,
"stepup": 2,
"sumosquat": 2,
"superman": 2
};
function exPhotoFrames(id){ return EX_PHOTOS[id] || 0; }
