/* ---------- pantry & recipe database (Монгол) ---------- */
// PANTRY_GROUPS: categorized ingredients the user can mark as "available at home"
const PANTRY_GROUPS = [
  {cat:'Мах, өндөг', items:[
    {tag:'beef', n:'Үхрийн мах', e:'🥩'},
    {tag:'mutton', n:'Хонины мах', e:'🍖'},
    {tag:'chicken', n:'Тахианы мах', e:'🍗'},
    {tag:'pork', n:'Гахайн мах', e:'🥓'},
    {tag:'egg', n:'Өндөг', e:'🥚'},
  ]},
  {cat:'Сүүн бүтээгдэхүүн', items:[
    {tag:'milk', n:'Сүү', e:'🥛'},
    {tag:'yogurt', n:'Тараг', e:'🍦'},
    {tag:'cheese', n:'Бяслаг', e:'🧀'},
  ]},
  {cat:'Үр тариа', items:[
    {tag:'rice', n:'Цагаан будаа', e:'🍚'},
    {tag:'flour', n:'Гурил', e:'🌾'},
    {tag:'noodle', n:'Гоймон', e:'🍜'},
    {tag:'oats', n:'Овъёос', e:'🥣'},
  ]},
  {cat:'Ногоо', items:[
    {tag:'potato', n:'Төмс', e:'🥔'},
    {tag:'carrot', n:'Лууван', e:'🥕'},
    {tag:'cabbage', n:'Байцаа', e:'🥬'},
    {tag:'onion', n:'Сонгино', e:'🧅'},
    {tag:'tomato', n:'Улаан лооль', e:'🍅'},
    {tag:'cucumber', n:'Өргөст хэмх', e:'🥒'},
    {tag:'garlic', n:'Саримс', e:'🧄'},
    {tag:'greens', n:'Ногоон ногоо', e:'🥗'},
  ]},
  {cat:'Бусад', items:[
    {tag:'beans', n:'Буурцаг', e:'🫘'},
    {tag:'fish', n:'Загас', e:'🐟'},
    {tag:'fruit', n:'Жимс', e:'🍎'},
    {tag:'nuts', n:'Самар', e:'🥜'},
  ]},
];

// RECIPES: meal = which diary slots it suits, needs = pantry tags used for meal-plan scoring,
// tags = diet categories ('mongol' | 'fatloss' | 'muscle')
const RECIPES = [
  {id:'buuz', n:'Бууз', e:'🥟', meal:['lunch','dinner'], needs:['mutton','flour','onion'], time:60, lvl:2,
    kcal:320, protein:14, carb:30, fat:16, tags:['mongol'],
    ingredients:['Хонины/үхрийн мах 500г','Гурил 300г','Сонгино 1–2','Давс, борц чинжүү'],
    steps:'Гурилаа усаар зуурч 20 мин амраа. Махаа жижиг хэрчиж сонгино, давс, борц нэмж зуур. Гурилаа нимгэн дэвсэж бөглөөд 15–20 мин уураар чанана.'},
  {id:'huushuur', n:'Хуушуур', e:'🥙', meal:['lunch','dinner','snack'], needs:['beef','flour','onion'], time:45, lvl:2,
    kcal:380, protein:12, carb:35, fat:22, tags:['mongol'],
    ingredients:['Үхрийн мах 400г','Гурил 300г','Сонгино 1','Тос (шарахад)'],
    steps:'Гурилаа зуурч амраа. Махаа жижиг хэрчиж сонгино, давс, борц нэмж зуур. Нимгэн дэвсэж бөглөөд халуун тосонд алтлаг болтол шарна.'},
  {id:'tsuivan', n:'Цуйван', e:'🍜', meal:['lunch','dinner'], needs:['noodle','beef','carrot','cabbage'], time:50, lvl:2,
    kcal:450, protein:18, carb:55, fat:18, tags:['mongol'],
    ingredients:['Гоймон 400г','Үхрийн мах 300г','Лууван 1–2','Байцаа 200г','Сонгино 1'],
    steps:'Гоймонгоо уураар жигнэж бэлд. Махаа жижиглэж шарж, сонгино лууваныг нэмж хуур. Байцаагаа нэмээд гоймонтойгоо хольж сайн хуур.'},
  {id:'friedrice', n:'Будаатай хуурга', e:'🍚', meal:['lunch','dinner'], needs:['rice','beef','carrot','onion'], time:40, lvl:1,
    kcal:420, protein:20, carb:50, fat:14, tags:['mongol','muscle'],
    ingredients:['Цагаан будаа 1.5 аяга','Үхрийн мах 300г','Лууван 1','Сонгино 1','Тос'],
    steps:'Будаагаа угааж чанаж бэлд. Махаа жижиглэж шарж, сонгино лууваныг нэмж хуур. Чанасан будаатайгаа хольж дахин хуур.'},
  {id:'noodlesoup', n:'Гурилтай шөл', e:'🍲', meal:['lunch','dinner'], needs:['flour','beef','potato','carrot'], time:45, lvl:1,
    kcal:380, protein:16, carb:45, fat:14, tags:['mongol'],
    ingredients:['Гурил 1.5 аяга','Үхрийн мах 250г','Төмс 2','Лууван 1','Ус'],
    steps:'Гурилаа нимгэн зуурч жижиг хэсэглэ. Махаа чанаж шөл бэлд. Төмс, лууваныг жижиглэн хийж, гурилаа нэмж буцалгана.'},
  {id:'oatmeal', n:'Овъёосны зутан', e:'🥣', meal:['breakfast'], needs:['oats','milk'], time:10, lvl:1,
    kcal:280, protein:10, carb:45, fat:7, tags:['fatloss'],
    ingredients:['Овъёос 1 аяга','Сүү 1.5 аяга','Давс/чихэр амтаар'],
    steps:'Сүүг буцалгаад овъёосоо хийж, бага галд 5–7 мин чанана. Хүссэнээрээ жимс, чихэр нэмж болно.'},
  {id:'eggfry', n:'Өндөгний хуурга', e:'🍳', meal:['breakfast'], needs:['egg','onion','tomato'], time:10, lvl:1,
    kcal:220, protein:14, carb:4, fat:16, tags:['fatloss','muscle'],
    ingredients:['Өндөг 2–3','Сонгино 1/2','Улаан лооль 1','Давс, тос'],
    steps:'Сонгино, лоолио жижиглэн тосонд хуур. Өндгөө сэгсэрч хийгээд бага галд эргүүлж болго.'},
  {id:'muesli', n:'Тарагтай мюсли', e:'🥄', meal:['breakfast','snack'], needs:['yogurt','oats'], time:5, lvl:1,
    kcal:250, protein:12, carb:35, fat:6, tags:['fatloss'],
    ingredients:['Цагаан тараг 1 аяга','Овъёос 1/2 аяга','Жимс/самар (хүсвэл)'],
    steps:'Тараг дээрээ овъёосоо хийгээд хольж 5 мин жийлээд идэх. Жимс, самраар чимж болно.'},
  {id:'potatoegg', n:'Шарсан төмс, өндөгтэй', e:'🥔', meal:['breakfast','lunch'], needs:['potato','egg'], time:25, lvl:1,
    kcal:350, protein:12, carb:40, fat:15, tags:['muscle'],
    ingredients:['Төмс 2–3','Өндөг 2','Сонгино 1/2','Тос, давс'],
    steps:'Төмсөө жижиглэн шарна. Бэлэн болоход сонгиноо нэмээд, дараа нь өндгийг нь хийж хольж болго.'},
  {id:'chickenfry', n:'Тахианы цээж шарсан, ногоотой', e:'🍗', meal:['lunch','dinner'], needs:['chicken','carrot','cabbage'], time:30, lvl:1,
    kcal:380, protein:35, carb:15, fat:18, tags:['fatloss','muscle'],
    ingredients:['Тахианы цээж 300г','Лууван 1','Байцаа 150г','Саримс, тос'],
    steps:'Тахиагаа жижиг хэрчиж, давс, саримсаар амтлаад тосонд шарна. Лууван, байцаагаа нэмж хамтад нь хуур.'},
  {id:'porkfry', n:'Гахайн мах ногоотой хуурга', e:'🥘', meal:['lunch','dinner'], needs:['pork','cabbage','onion','garlic'], time:35, lvl:2,
    kcal:410, protein:24, carb:18, fat:26, tags:['mongol'],
    ingredients:['Гахайн мах 300г','Байцаа 200г','Сонгино 1','Саримс 2–3 ширхэг'],
    steps:'Гахайн махаа жижиглэн шарна. Сонгино, саримс нэмж амтлаад, байцаагаа хийж бэлэн болтол хуур.'},
  {id:'salad', n:'Ногооны салат', e:'🥗', meal:['lunch','dinner','snack'], needs:['cucumber','tomato','greens'], time:10, lvl:1,
    kcal:120, protein:3, carb:12, fat:7, tags:['fatloss'],
    ingredients:['Өргөст хэмх 1','Улаан лооль 1','Ногоон салатны навч','Тос, давс, лимон'],
    steps:'Бүх ногоогоо жижиглэн зүснэ. Тос, давс, бага лимоны шүүсээр амтлаж хольно.'},
  {id:'cheesenoodle', n:'Бяслагтай гоймон', e:'🧀', meal:['lunch','dinner'], needs:['noodle','cheese','milk'], time:20, lvl:1,
    kcal:400, protein:16, carb:50, fat:15, tags:['mongol'],
    ingredients:['Гоймон 250г','Бяслаг 100г','Сүү 1/2 аяга','Тос'],
    steps:'Гоймоноо чанана. Сүү, бяслагаа бага галд хайлуулж соус хийгээд гоймонтойгоо хольно.'},
  {id:'beansoup', n:'Буурцагтай шөл', e:'🫘', meal:['lunch','dinner'], needs:['beans','carrot','potato','onion'], time:40, lvl:2,
    kcal:320, protein:16, carb:40, fat:10, tags:['mongol','fatloss'],
    ingredients:['Буурцаг 1 аяга (норгосон)','Төмс 2','Лууван 1','Сонгино 1'],
    steps:'Норгосон буурцгаа угааж чанана. Хагас болоход төмс, лууван, сонгиноо нэмж бэлэн болтол чанана.'},
  {id:'yogurtfruit', n:'Тараг, жимстэй', e:'🍓', meal:['snack'], needs:['yogurt'], time:3, lvl:1,
    kcal:150, protein:8, carb:20, fat:4, tags:['fatloss'],
    ingredients:['Цагаан тараг 1 аяга','Жимс (байгаа бол)'],
    steps:'Тарагаа аяганд хийж, байгаа жимсээ нэмж шууд идэж болно.'},

  /* ---- Монгол хоол (нэмэлт) ---- */
  {id:'khorkhog', n:'Хорхог', e:'🍖', meal:['lunch','dinner'], needs:['mutton','potato','carrot','onion'], time:120, lvl:3,
    kcal:520, protein:32, carb:25, fat:32, tags:['mongol'],
    ingredients:['Хонины мах ясаар 1.5кг','Төмс 4–5','Лууван 2','Сонгино 2','Халсан чулуу, давс'],
    steps:'Махаа том хэсэг болгон зүсч саванд хийнэ. Халуун чулуу, төмс, лууван, сонгинотой ээлжлэн давхарлаж давс цацна. Сав битүүмжлээд 1–1.5 цаг чанана.'},
  {id:'boortsog', n:'Боорцог', e:'🥯', meal:['breakfast','snack'], needs:['flour','milk'], time:40, lvl:2,
    kcal:230, protein:5, carb:30, fat:10, tags:['mongol'],
    ingredients:['Гурил 2 аяга','Сүү 1/2 аяга','Өндөг 1','Сод, давс','Тос (шарахад)'],
    steps:'Гурил, сүү, өндөг, давс, содыг хольж зуурна. 30 мин амраагаад жижиг хэсэг болгон хэлбэржүүлж халуун тосонд алтлаг болтол шарна.'},
  {id:'bantan', n:'Бантан', e:'🥣', meal:['breakfast','lunch'], needs:['flour','beef','onion'], time:30, lvl:1,
    kcal:300, protein:13, carb:35, fat:11, tags:['mongol'],
    ingredients:['Гурил 1 аяга','Үхрийн мах 150г','Сонгино 1/2','Ус, давс'],
    steps:'Махаа жижиглэн чанаж шөл бэлд. Гурилаа усаар сийрэг зуурч буцалж буй шөл рүү нимгэн урсгана. Сонгино нэмж улам чанана.'},
  {id:'zutan', n:'Зутан (мах, будаатай)', e:'🍵', meal:['breakfast','lunch'], needs:['rice','beef','onion'], time:35, lvl:1,
    kcal:340, protein:14, carb:42, fat:11, tags:['mongol'],
    ingredients:['Цагаан будаа 1/2 аяга','Үхрийн мах 150г','Сонгино 1/2','Ус, давс'],
    steps:'Махаа жижиглэн усанд хийж чанана. Будаагаа угаагаад нэмж зөөлөн болтол удаан галд чанана. Сонгино, давсаар амтлана.'},
  {id:'friedbansh', n:'Шарсан банш', e:'🫓', meal:['lunch','snack'], needs:['beef','flour','onion'], time:50, lvl:2,
    kcal:330, protein:13, carb:30, fat:18, tags:['mongol'],
    ingredients:['Үхрийн мах 250г','Гурил 200г','Сонгино 1','Тос (шарахад)'],
    steps:'Бууз шиг жижиг банш хийж бэлдэнэ. Халуун тосонд алтлаг болтол шарж гаргана.'},
  {id:'lamjaa', n:'Ламжаа', e:'🍝', meal:['lunch','dinner'], needs:['noodle','beef','cabbage','carrot'], time:45, lvl:2,
    kcal:400, protein:15, carb:48, fat:15, tags:['mongol'],
    ingredients:['Гоймон 300г','Үхрийн мах 200г','Байцаа 150г','Лууван 1','Сонгино 1'],
    steps:'Гоймоноо чанаж бэлд. Махаа шарж сонгино, лууван нэмж хуур. Байцаагаа нэмээд гоймонтойгоо хольж улам хуур.'},
  {id:'aaruul', n:'Ааруул', e:'🥮', meal:['snack'], needs:['milk'], time:5, lvl:1,
    kcal:120, protein:9, carb:10, fat:5, tags:['mongol','fatloss'],
    ingredients:['Аарц/ааруул 80г'],
    steps:'Бэлэн ааруулаа шууд иднэ. Удаан хадгалагддаг тул гэрээсээ авч явахад тохиромжтой зууш.'},
  {id:'milktea', n:'Сүүтэй цай, боорцогтой', e:'☕', meal:['breakfast'], needs:['milk','flour'], time:15, lvl:1,
    kcal:260, protein:6, carb:32, fat:11, tags:['mongol'],
    ingredients:['Сүүтэй цай 1 аяга','Боорцог 2–3','Тараг (хүсвэл)'],
    steps:'Сүүтэй цайгаа чанаад, бэлэн боорцогтой хамт өглөөний цайнд үйлчил.'},
  {id:'muttonpotatosoup', n:'Хонины махтай төмсний шөл', e:'🍲', meal:['lunch','dinner'], needs:['mutton','potato','carrot','onion'], time:50, lvl:1,
    kcal:360, protein:18, carb:30, fat:16, tags:['mongol'],
    ingredients:['Хонины мах 250г','Төмс 2','Лууван 1','Сонгино 1','Ус, давс'],
    steps:'Махаа жижиглэн усанд хийж чанана. Төмс, лууван, сонгиноо нэмж зөөлөн болтол чанаад давсална.'},

  /* ---- Жин хасах хоол ---- */
  {id:'steamedfish', n:'Уураар хайрсан загас, ногоотой', e:'🐟', meal:['lunch','dinner'], needs:['fish','carrot','cabbage'], time:25, lvl:1,
    kcal:230, protein:28, carb:10, fat:8, tags:['fatloss','muscle'],
    ingredients:['Загас 250г','Лууван 1','Байцаа 150г','Давс, лимон'],
    steps:'Загасаа давс, лимоны шүүсээр амтлаад ногоотойгоо хамт уураар 15–20 мин хайрна.'},
  {id:'vegsoup', n:'Ногооны шөл', e:'🥣', meal:['lunch','dinner'], needs:['potato','carrot','cabbage','onion'], time:35, lvl:1,
    kcal:160, protein:5, carb:25, fat:5, tags:['fatloss','mongol'],
    ingredients:['Төмс 1','Лууван 1','Байцаа 150г','Сонгино 1/2','Ус, давс'],
    steps:'Бүх ногоогоо жижиглэн усанд хийж зөөлөн болтол чанана. Давс, борц чинжүүгээр амтлана.'},
  {id:'eggwhiteveg', n:'Өндөгний цагаантай ногоотой шарсан', e:'🍳', meal:['breakfast'], needs:['egg','tomato','greens'], time:12, lvl:1,
    kcal:160, protein:16, carb:5, fat:7, tags:['fatloss','muscle'],
    ingredients:['Өндөгний цагаан 4–5ш','Улаан лооль 1','Ногоон ногоо багц','Давс, тос бага зэрэг'],
    steps:'Өндөгний цагааныг зөвхөн ялгаж аваад ногоотойгоо хольж бага тостой тавган дээр шарна.'},
  {id:'cheesecucumber', n:'Бяслаг, өргөст хэмхтэй', e:'🥒', meal:['breakfast','snack'], needs:['cheese','cucumber'], time:5, lvl:1,
    kcal:140, protein:14, carb:5, fat:7, tags:['fatloss','muscle'],
    ingredients:['Бяслаг 100г','Өргөст хэмх 1','Давс'],
    steps:'Бяслагаа зүссэн хэмхтэйгээ хамт идэж болно. Хурдан бэлддэг, уураг өндөртэй зууш.'},
  {id:'tunasalad', n:'Туна загасны салат', e:'🥗', meal:['lunch','dinner','snack'], needs:['fish','cucumber','tomato'], time:10, lvl:1,
    kcal:220, protein:24, carb:8, fat:10, tags:['fatloss','muscle'],
    ingredients:['Конс загас (туна) 1 банк','Өргөст хэмх 1','Улаан лооль 1','Тос, лимон, давс'],
    steps:'Загасаа сэвсэлж жижигхэн зүссэн ногоотойгоо хольж тос, лимоны шүүсээр амтлана.'},
  {id:'fruitnuts', n:'Жимс, самрын зууш', e:'🍎', meal:['snack'], needs:['fruit','nuts'], time:2, lvl:1,
    kcal:180, protein:4, carb:24, fat:9, tags:['fatloss'],
    ingredients:['Алим/банана 1','Самар 20г'],
    steps:'Жимсээ самартайгаа хамт шууд идэж болно. Хооллолтын хооронд цатгалан өгөх зууш.'},
  {id:'vegfry', n:'Ногооны хуурга', e:'🥦', meal:['lunch','dinner'], needs:['cabbage','carrot','onion','garlic'], time:20, lvl:1,
    kcal:150, protein:4, carb:18, fat:7, tags:['fatloss','mongol'],
    ingredients:['Байцаа 200г','Лууван 1','Сонгино 1/2','Саримс 1–2','Тос бага зэрэг'],
    steps:'Бүх ногоогоо жижиглэн бага тостой тавган дээр хурдан хуур. Давс, борц чинжүүгээр амтлана.'},
  {id:'chickenvegsoup', n:'Тахиа, ногоотой шөл', e:'🍲', meal:['lunch','dinner'], needs:['chicken','carrot','potato'], time:40, lvl:1,
    kcal:250, protein:26, carb:18, fat:7, tags:['fatloss','muscle'],
    ingredients:['Тахианы мах 200г','Төмс 1','Лууван 1','Ус, давс'],
    steps:'Тахиагаа жижиглэн усанд хийж чанана. Төмс, лууваныг нэмж зөөлөн болтол чанаад давсална.'},
  {id:'boiledeggveg', n:'Хайрсан өндөг, ногоотой', e:'🥚', meal:['breakfast','snack'], needs:['egg','greens'], time:10, lvl:1,
    kcal:180, protein:13, carb:4, fat:12, tags:['fatloss','muscle'],
    ingredients:['Өндөг 2','Ногоон ногоо багц','Давс'],
    steps:'Өндгөө чанаж хальслана. Ногоон ногоотойгоо хамт давслан идэж болно.'},
  {id:'rawveg', n:'Түүхий ногоо, зууш', e:'🥕', meal:['snack'], needs:['carrot','cucumber'], time:3, lvl:1,
    kcal:60, protein:2, carb:12, fat:0, tags:['fatloss'],
    ingredients:['Лууван 1','Өргөст хэмх 1'],
    steps:'Ногоогоо урт зүснэ. Шууд эсвэл бага зэрэг давсаар амтлан идэж болно.'},

  /* ---- Булчин нэмэх хоол ---- */
  {id:'proteinsmoothie', n:'Уураг, жимстэй смузи', e:'🥤', meal:['breakfast','snack'], needs:['milk','oats','fruit','nuts'], time:5, lvl:1,
    kcal:380, protein:16, carb:50, fat:12, tags:['muscle'],
    ingredients:['Сүү 1.5 аяга','Овъёос 1/2 аяга','Банана/жимс 1','Самрын тос 1 халбага'],
    steps:'Бүх орцыг блендерт хийж жигд болтол хутгана. Дасгалын дараа уухад тохиромжтой.'},
  {id:'chickenriceveg', n:'Тахиа, будаа, ногоотой', e:'🍛', meal:['lunch','dinner'], needs:['chicken','rice','carrot','cabbage'], time:35, lvl:1,
    kcal:480, protein:38, carb:50, fat:14, tags:['muscle'],
    ingredients:['Тахианы цээж 250г','Цагаан будаа 1 аяга','Лууван 1','Байцаа 100г'],
    steps:'Будаагаа чанана. Тахиагаа жижиглэн шарж лууван, байцаатайгаа хуурна. Будаатайгаа хольж үйлчил.'},
  {id:'beefpotato', n:'Үхрийн мах, төмстэй', e:'🥩', meal:['lunch','dinner'], needs:['beef','potato','onion'], time:45, lvl:2,
    kcal:500, protein:32, carb:35, fat:24, tags:['muscle','mongol'],
    ingredients:['Үхрийн мах 300г','Төмс 3','Сонгино 1','Тос'],
    steps:'Махаа жижиглэн шарна. Төмсөө нэмж хамт хуурч, сонгинотойгоо амтлан бэлэн болтол болго.'},
  {id:'fishrice', n:'Загас, будаатай', e:'🐠', meal:['lunch','dinner'], needs:['fish','rice'], time:30, lvl:1,
    kcal:430, protein:30, carb:45, fat:12, tags:['muscle','fatloss'],
    ingredients:['Загас 250г','Цагаан будаа 1 аяга','Лимон, давс'],
    steps:'Будаагаа чанана. Загасаа давс, лимоны шүүсээр амтлаад шарж эсвэл уураар хайрна. Будаатайгаа хамт үйлчил.'},
  {id:'muttonrice', n:'Хонины мах, будаатай', e:'🍚', meal:['lunch','dinner'], needs:['mutton','rice','onion'], time:50, lvl:2,
    kcal:520, protein:30, carb:48, fat:22, tags:['muscle','mongol'],
    ingredients:['Хонины мах 300г','Цагаан будаа 1 аяга','Сонгино 1','Тос'],
    steps:'Махаа жижиглэн шарна. Сонгино нэмж амтлаад чанасан будаатайгаа хольж дахин хуур.'},
  {id:'eggcheesebread', n:'Өндөг, бяслагтай талх', e:'🥪', meal:['breakfast'], needs:['egg','cheese','flour'], time:12, lvl:1,
    kcal:380, protein:20, carb:30, fat:18, tags:['muscle'],
    ingredients:['Өндөг 2–3','Бяслаг 50г','Талх 2 хэсэг'],
    steps:'Өндгөө шарна. Талхан дээрээ бяслаг, шарсан өндгөө тавьж идэж болно.'},
  {id:'beefbeanstew', n:'Үхрийн мах, буурцагтай', e:'🍲', meal:['lunch','dinner'], needs:['beef','beans','onion','carrot'], time:55, lvl:2,
    kcal:460, protein:30, carb:35, fat:18, tags:['muscle'],
    ingredients:['Үхрийн мах 250г','Буурцаг 1 аяга (норгосон)','Сонгино 1','Лууван 1'],
    steps:'Буурцгаа норгож бэлдэнэ. Махаа шарж сонгино, лууван нэмж хуур. Буурцгаа хийж зөөлөн болтол чанана.'},
  {id:'yogurtgranola', n:'Тараг, гранола, самартай', e:'🥣', meal:['breakfast','snack'], needs:['yogurt','oats','nuts'], time:5, lvl:1,
    kcal:340, protein:16, carb:38, fat:12, tags:['muscle','fatloss'],
    ingredients:['Цагаан тараг 1.5 аяга','Овъёос 1/2 аяга','Самар 20г','Зөгийн бал (хүсвэл)'],
    steps:'Тараг дээрээ овъёос, самраа хийж хольно. Хүсвэл зөгийн балаар чимж болно.'},
  {id:'porkrice', n:'Гахайн мах, будаатай', e:'🍚', meal:['lunch','dinner'], needs:['pork','rice','onion','garlic'], time:40, lvl:2,
    kcal:490, protein:26, carb:50, fat:20, tags:['muscle'],
    ingredients:['Гахайн мах 250г','Цагаан будаа 1 аяга','Сонгино 1','Саримс 2'],
    steps:'Махаа жижиглэн саримс, сонгинотой шарна. Чанасан будаатайгаа хольж үйлчил.'},
  {id:'eggpotatocheese', n:'Өндөг, төмс, бяслагтай', e:'🍳', meal:['breakfast','lunch'], needs:['egg','potato','cheese'], time:30, lvl:2,
    kcal:420, protein:20, carb:35, fat:22, tags:['muscle'],
    ingredients:['Өндөг 3','Төмс 2','Бяслаг 50г','Тос, давс'],
    steps:'Төмсөө жижиглэн шарна. Өндөг, бяслагаа нэмж хамт болтол болгоно.'},
  {id:'chickennoodle', n:'Тахианы мах, гоймонтой', e:'🍜', meal:['lunch','dinner'], needs:['chicken','noodle','carrot'], time:35, lvl:1,
    kcal:470, protein:32, carb:48, fat:16, tags:['muscle'],
    ingredients:['Тахианы мах 250г','Гоймон 250г','Лууван 1','Сонгино 1/2'],
    steps:'Гоймоноо чанана. Тахиагаа жижиглэн шарж лууван, сонгинотой хуур. Гоймонтойгоо хольж үйлчил.'},
];

const RECIPE_CATS = {mongol:'🇲🇳 Монгол хоол', fatloss:'🔥 Жин хасах', muscle:'💪 Булчин нэмэх'};
const MEAL_NAMES = {breakfast:'Өглөө', lunch:'Өдөр', dinner:'Орой', snack:'Зууш'};
function youtubeSearchUrl(name){ return 'https://www.youtube.com/results?search_query=' + encodeURIComponent(name + ' хийх заавар'); }
