/* ---------- pantry & recipe database (Монгол) ---------- */
// PANTRY_GROUPS: categorized ingredients the user can mark as "available at home"
const PANTRY_GROUPS = [
  {cat:'Мах, өндөг', items:[
    {tag:'beef', n:'Үхрийн мах', e:'🥩'},
    {tag:'mutton', n:'Хонины мах', e:'🍖'},
    {tag:'chicken', n:'Тахианы мах', e:'🍗'},
    {tag:'pork', n:'Гахайн мах', e:'🥓'},
    {tag:'egg', n:'Өндөг', e:'🥚'},
  ]},
  {cat:'Сүүн бүтээгдэхүүн', items:[
    {tag:'milk', n:'Сүү', e:'🥛'},
    {tag:'yogurt', n:'Тараг', e:'🍦'},
    {tag:'cheese', n:'Бяслаг', e:'🧀'},
  ]},
  {cat:'Үр тариа', items:[
    {tag:'rice', n:'Цагаан будаа', e:'🍚'},
    {tag:'flour', n:'Гурил', e:'🌾'},
    {tag:'noodle', n:'Гоймон', e:'🍜'},
    {tag:'oats', n:'Овъёос', e:'🥣'},
  ]},
  {cat:'Ногоо', items:[
    {tag:'potato', n:'Төмс', e:'🥔'},
    {tag:'carrot', n:'Лууван', e:'🥕'},
    {tag:'cabbage', n:'Байцаа', e:'🥬'},
    {tag:'onion', n:'Сонгино', e:'🧅'},
    {tag:'tomato', n:'Улаан лооль', e:'🍅'},
    {tag:'cucumber', n:'Өргөст хэмх', e:'🥒'},
    {tag:'garlic', n:'Саримс', e:'🧄'},
    {tag:'greens', n:'Ногоон ногоо', e:'🥗'},
  ]},
  {cat:'Бусад', items:[
    {tag:'beans', n:'Буурцаг', e:'🫘'},
  ]},
];

// RECIPES: meal = which diary slots it suits, needs = pantry tags used for meal-plan scoring
const RECIPES = [
  {id:'buuz', n:'Бууз', e:'🥟', meal:['lunch','dinner'], needs:['mutton','flour','onion'], time:60, lvl:2,
    kcal:320, protein:14, carb:30, fat:16,
    ingredients:['Хонины/үхрийн мах 500г','Гурил 300г','Сонгино 1–2','Давс, борц чинжүү'],
    steps:'Гурилаа усаар зуурч 20 мин амраа. Махаа жижиг хэрчиж сонгино, давс, борц нэмж зуур. Гурилаа нимгэн дэвсэж бөглөөд 15–20 мин уураар чанана.'},
  {id:'huushuur', n:'Хуушуур', e:'🥙', meal:['lunch','dinner','snack'], needs:['beef','flour','onion'], time:45, lvl:2,
    kcal:380, protein:12, carb:35, fat:22,
    ingredients:['Үхрийн мах 400г','Гурил 300г','Сонгино 1','Тос (шарахад)'],
    steps:'Гурилаа зуурч амраа. Махаа жижиг хэрчиж сонгино, давс, борц нэмж зуур. Нимгэн дэвсэж бөглөөд халуун тосонд алтлаг болтол шарна.'},
  {id:'tsuivan', n:'Цуйван', e:'🍜', meal:['lunch','dinner'], needs:['noodle','beef','carrot','cabbage'], time:50, lvl:2,
    kcal:450, protein:18, carb:55, fat:18,
    ingredients:['Гоймон 400г','Үхрийн мах 300г','Лууван 1–2','Байцаа 200г','Сонгино 1'],
    steps:'Гоймонгоо уураар жигнэж бэлд. Махаа жижиглэж шарж, сонгино лууваныг нэмж хуур. Байцаагаа нэмээд гоймонтойгоо хольж сайн хуур.'},
  {id:'friedrice', n:'Будаатай хуурга', e:'🍚', meal:['lunch','dinner'], needs:['rice','beef','carrot','onion'], time:40, lvl:1,
    kcal:420, protein:20, carb:50, fat:14,
    ingredients:['Цагаан будаа 1.5 аяга','Үхрийн мах 300г','Лууван 1','Сонгино 1','Тос'],
    steps:'Будаагаа угааж чанаж бэлд. Махаа жижиглэж шарж, сонгино лууваныг нэмж хуур. Чанасан будаатайгаа хольж дахин хуур.'},
  {id:'noodlesoup', n:'Гурилтай шөл', e:'🍲', meal:['lunch','dinner'], needs:['flour','beef','potato','carrot'], time:45, lvl:1,
    kcal:380, protein:16, carb:45, fat:14,
    ingredients:['Гурил 1.5 аяга','Үхрийн мах 250г','Төмс 2','Лууван 1','Ус'],
    steps:'Гурилаа нимгэн зуурч жижиг хэсэглэ. Махаа чанаж шөл бэлд. Төмс, лууваныг жижиглэн хийж, гурилаа нэмж буцалгана.'},
  {id:'oatmeal', n:'Овъёосны зутан', e:'🥣', meal:['breakfast'], needs:['oats','milk'], time:10, lvl:1,
    kcal:280, protein:10, carb:45, fat:7,
    ingredients:['Овъёос 1 аяга','Сүү 1.5 аяга','Давс/чихэр амтаар'],
    steps:'Сүүг буцалгаад овъёосоо хийж, бага галд 5–7 мин чанана. Хүссэнээрээ жимс, чихэр нэмж болно.'},
  {id:'eggfry', n:'Өндөгний хуурга', e:'🍳', meal:['breakfast'], needs:['egg','onion','tomato'], time:10, lvl:1,
    kcal:220, protein:14, carb:4, fat:16,
    ingredients:['Өндөг 2–3','Сонгино 1/2','Улаан лооль 1','Давс, тос'],
    steps:'Сонгино, лоолио жижиглэн тосонд хуур. Өндгөө сэгсэрч хийгээд бага галд эргүүлж болго.'},
  {id:'muesli', n:'Тарагтай мюсли', e:'🥄', meal:['breakfast','snack'], needs:['yogurt','oats'], time:5, lvl:1,
    kcal:250, protein:12, carb:35, fat:6,
    ingredients:['Цагаан тараг 1 аяга','Овъёос 1/2 аяга','Жимс/самар (хүсвэл)'],
    steps:'Тараг дээрээ овъёосоо хийгээд хольж 5 мин жийлээд идэх. Жимс, самраар чимж болно.'},
  {id:'potatoegg', n:'Шарсан төмс, өндөгтэй', e:'🥔', meal:['breakfast','lunch'], needs:['potato','egg'], time:25, lvl:1,
    kcal:350, protein:12, carb:40, fat:15,
    ingredients:['Төмс 2–3','Өндөг 2','Сонгино 1/2','Тос, давс'],
    steps:'Төмсөө жижиглэн шарна. Бэлэн болоход сонгиноо нэмээд, дараа нь өндгийг нь хийж хольж болго.'},
  {id:'chickenfry', n:'Тахианы цээж шарсан, ногоотой', e:'🍗', meal:['lunch','dinner'], needs:['chicken','carrot','cabbage'], time:30, lvl:1,
    kcal:380, protein:35, carb:15, fat:18,
    ingredients:['Тахианы цээж 300г','Лууван 1','Байцаа 150г','Саримс, тос'],
    steps:'Тахиагаа жижиг хэрчиж, давс, саримсаар амтлаад тосонд шарна. Лууван, байцаагаа нэмж хамтад нь хуур.'},
  {id:'porkfry', n:'Гахайн мах ногоотой хуурга', e:'🥘', meal:['lunch','dinner'], needs:['pork','cabbage','onion','garlic'], time:35, lvl:2,
    kcal:410, protein:24, carb:18, fat:26,
    ingredients:['Гахайн мах 300г','Байцаа 200г','Сонгино 1','Саримс 2–3 ширхэг'],
    steps:'Гахайн махаа жижиглэн шарна. Сонгино, саримс нэмж амтлаад, байцаагаа хийж бэлэн болтол хуур.'},
  {id:'salad', n:'Ногооны салат', e:'🥗', meal:['lunch','dinner','snack'], needs:['cucumber','tomato','greens'], time:10, lvl:1,
    kcal:120, protein:3, carb:12, fat:7,
    ingredients:['Өргөст хэмх 1','Улаан лооль 1','Ногоон салатны навч','Тос, давс, лимон'],
    steps:'Бүх ногоогоо жижиглэн зүснэ. Тос, давс, бага лимоны шүүсээр амтлаж хольно.'},
  {id:'cheesenoodle', n:'Бяслагтай гоймон', e:'🧀', meal:['lunch','dinner'], needs:['noodle','cheese','milk'], time:20, lvl:1,
    kcal:400, protein:16, carb:50, fat:15,
    ingredients:['Гоймон 250г','Бяслаг 100г','Сүү 1/2 аяга','Тос'],
    steps:'Гоймоноо чанана. Сүү, бяслагаа бага галд хайлуулж соус хийгээд гоймонтойгоо хольно.'},
  {id:'beansoup', n:'Буурцагтай шөл', e:'🫘', meal:['lunch','dinner'], needs:['beans','carrot','potato','onion'], time:40, lvl:2,
    kcal:320, protein:16, carb:40, fat:10,
    ingredients:['Буурцаг 1 аяга (норгосон)','Төмс 2','Лууван 1','Сонгино 1'],
    steps:'Норгосон буурцгаа угааж чанана. Хагас болоход төмс, лууван, сонгиноо нэмж бэлэн болтол чанана.'},
  {id:'yogurtfruit', n:'Тараг, жимстэй', e:'🍓', meal:['snack'], needs:['yogurt'], time:3, lvl:1,
    kcal:150, protein:8, carb:20, fat:4,
    ingredients:['Цагаан тараг 1 аяга','Жимс (байгаа бол)'],
    steps:'Тарагаа аяганд хийж, байгаа жимсээ нэмж шууд идэж болно.'},
];

const MEAL_NAMES = {breakfast:'Өглөө', lunch:'Өдөр', dinner:'Орой', snack:'Зууш'};
function youtubeSearchUrl(name){ return 'https://www.youtube.com/results?search_query=' + encodeURIComponent(name + ' хийх заавар'); }
